/**
 * AI Match Analysis Generation
 *
 * Env vars:
 *   ANTHROPIC_API_KEY – Claude API key (optional)
 *   AI_MOCK_MODE      – "true" to use mock analysis
 *
 * Generates match previews and recaps from structured data only.
 * Claude is asked to return a strict JSON object — never free-form text.
 */

import type { Fixture, MatchDetail, H2HData, TeamStatistics, FixturePlayerStats } from "./football/types";

export type AnalysisLocale = "en" | "ko";

export interface AnalysisPrediction {
  outcome: "home" | "away" | "draw";
  label: string;
  confidence: number; // 0–100
}

export interface AnalysisTip {
  label: string;
  labelKo: string;
}

export interface AnalysisKeyFactor {
  icon: string;
  label: string;
  labelKo: string;
  value: string;
  valueKo: string;
}

export interface MatchAnalysis {
  id: string;
  fixtureId: number;
  type: "preview" | "recap";
  locale: AnalysisLocale;
  title: string;
  slug: string;
  summary: string;
  insight: string;
  prediction?: AnalysisPrediction;
  keyFactors?: AnalysisKeyFactor[];
  tips: AnalysisTip[];
  aiModel: string;
  generatedAt: string;
  disclaimer: string;
  isAiGenerated: boolean;
}

/** Optional enrichment data from API-Football endpoints */
export interface AnalysisEnrichmentData {
  h2h?: H2HData;
  homeStats?: TeamStatistics | null;
  awayStats?: TeamStatistics | null;
  /** Per-player fixture stats — used for MOM auto-selection in recaps */
  fixturePlayers?: FixturePlayerStats[];
}

export interface AnalysisGenerateInput {
  fixture: Fixture | MatchDetail;
  type: "preview" | "recap";
  locale?: AnalysisLocale;
  enrichment?: AnalysisEnrichmentData;
}

export const isAiMockMode =
  process.env.AI_MOCK_MODE === "true" || !process.env.ANTHROPIC_API_KEY;

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

/** Stable, human-readable slug that avoids fixture IDs and locale noise.
 *  Format: {home}-vs-{away}-{YYYY-MM-DD}-{type}
 *  e.g.  arsenal-vs-bournemouth-2026-03-23-preview
 */
export function buildSlug(
  home: string,
  away: string,
  date: string,        // ISO date string
  type: "preview" | "recap"
): string {
  const day = date.split("T")[0] ?? date; // "2026-03-23"
  return `${slugify(home)}-vs-${slugify(away)}-${day}-${type}`;
}

// ─── Mock ─────────────────────────────────────────────────────────────────────

function getMockAnalysis(input: AnalysisGenerateInput): MatchAnalysis {
  const { fixture, type, locale = "en" } = input;
  const isKo = locale === "ko";
  const homeTeam = fixture.homeTeam.name;
  const awayTeam = fixture.awayTeam.name;
  const title =
    type === "preview"
      ? isKo
        ? `${homeTeam} vs ${awayTeam} 경기 프리뷰`
        : `${homeTeam} vs ${awayTeam} Match Preview`
      : isKo
        ? `${homeTeam} vs ${awayTeam} 경기 결과`
        : `${homeTeam} vs ${awayTeam} Match Recap`;

  return {
    id: `mock-${fixture.id}-${type}-${locale}`,
    fixtureId: fixture.id,
    type,
    locale,
    title,
    slug: buildSlug(homeTeam, awayTeam, fixture.date, type),
    summary: isKo
      ? `이 분석은 KickVista AI가 구조화된 경기 데이터를 기반으로 생성한 예시 분석입니다.`
      : `This is a sample analysis generated by KickVista AI based on structured match data.`,
    insight: isKo
      ? `최근 맞대결 기록과 홈/원정 폼을 바탕으로 분석한 결과, 이 경기는 팽팽한 접전이 예상됩니다.`
      : `Based on recent head-to-head records and home/away form, this match is expected to be closely contested.`,
    prediction: {
      outcome: "home",
      label: isKo ? "홈 팀 승리" : "Home Win",
      confidence: 58,
    },
    keyFactors: [
      { icon: "📊", label: "Form (Last 5)", labelKo: "최근 5경기 폼", value: "W W D L W", valueKo: "승 승 무 패 승" },
      { icon: "🏟️", label: "Venue",         labelKo: "경기장",        value: "Home",      valueKo: "홈" },
    ],
    tips: [
      { label: "Both Teams to Score", labelKo: "양팀 득점" },
      { label: "Over 2.5 Goals",      labelKo: "2.5골 오버" },
    ],
    aiModel: "KickVista AI (Mock)",
    generatedAt: new Date().toISOString(),
    disclaimer: isKo
      ? "AI 분석은 오락 목적으로만 제공됩니다. 과거 성과는 미래 결과를 보장하지 않습니다."
      : "AI predictions are for entertainment purposes only. Past performance does not guarantee future results.",
    isAiGenerated: true,
  };
}

// ─── Claude API ───────────────────────────────────────────────────────────────

const JSON_SCHEMA = `{
  "title": "string — engaging article title",
  "summary": "string — 2–3 sentence summary",
  "insight": "string — full analysis body, 4–6 paragraphs separated by \\n\\n",
  "prediction": { "outcome": "home|away|draw", "label": "string", "confidence": 0–100 },
  "keyFactors": [
    { "icon": "emoji", "label": "English label", "labelKo": "Korean label", "value": "English value", "valueKo": "Korean value" }
  ],
  "tips": [
    { "label": "English tip", "labelKo": "Korean tip" }
  ]
}`;

/** Find the Man of the Match from fixture player stats (highest rating). */
function findMOM(players: FixturePlayerStats[]): FixturePlayerStats | null {
  const rated = players.filter((p) => p.rating !== null && p.minutesPlayed >= 45);
  if (!rated.length) return null;
  return rated.reduce((best, p) => (p.rating! > best.rating! ? p : best));
}

function buildH2HSummary(h2h: H2HData, homeName: string, awayName: string): string {
  const { summary, matches } = h2h;
  const total = summary.team1Wins + summary.team2Wins + summary.draws;
  if (total === 0) return "No head-to-head data available.";
  const recent = matches.slice(0, 5).map(
    (m) => `${m.homeTeam} ${m.homeScore}–${m.awayScore} ${m.awayTeam} (${m.date.split("T")[0]})`
  ).join(", ");
  return `H2H last ${total} meetings — ${homeName}: ${summary.team1Wins}W | Draws: ${summary.draws} | ${awayName}: ${summary.team2Wins}W. Recent: ${recent}`;
}

function buildTeamStatsSummary(stats: TeamStatistics, teamName: string, isHome: boolean): string {
  const venue = isHome ? "home" : "away";
  return `${teamName} (${venue}): Form="${stats.form.slice(-5)}" | W${stats.wins.total}/D${stats.draws.total}/L${stats.losses.total} | Avg goals scored=${stats.avgGoalsFor} conceded=${stats.avgGoalsAgainst} | Clean sheets=${stats.cleanSheets.total}`;
}

function buildPrompt(input: AnalysisGenerateInput): string {
  const { fixture, type, locale = "en", enrichment = {} } = input;
  const isKo = locale === "ko";
  const home = fixture.homeTeam.name;
  const away = fixture.awayTeam.name;

  const lang = isKo
    ? "Write ALL string values in Korean. Only 'label' / 'value' fields in keyFactors and tips may keep an English parallel."
    : "Write ALL string values in English.";

  if (type === "preview") {
    const h2hLine = enrichment.h2h
      ? buildH2HSummary(enrichment.h2h, home, away)
      : "Head-to-head data not available.";
    const homeStatsLine = enrichment.homeStats
      ? buildTeamStatsSummary(enrichment.homeStats, home, true)
      : `${home}: Team statistics not available.`;
    const awayStatsLine = enrichment.awayStats
      ? buildTeamStatsSummary(enrichment.awayStats, away, false)
      : `${away}: Team statistics not available.`;

    return `You are a professional football analyst. Write a data-driven match preview.
${lang}
Return ONLY a valid JSON object matching this schema — no markdown, no extra text:
${JSON_SCHEMA}

Match data:
- Home: ${home}
- Away: ${away}
- Date: ${fixture.date}
- League: ${fixture.leagueSlug}
- Status: ${fixture.status}

Statistical context:
- ${h2hLine}
- ${homeStatsLine}
- ${awayStatsLine}

Rules:
- Use the statistical context above to back up your analysis with real data
- insight must have 4–6 paragraphs (\\n\\n separated)
- prediction.confidence must be 40–80 (realistic range)
- keyFactors: exactly 3 items derived from the stats above (form, H2H record, expected goals, etc.)
- tips: exactly 2 items
- Do NOT mention gambling or betting`;
  }

  const md = fixture as MatchDetail;
  const score = `${md.homeScore ?? 0}–${md.awayScore ?? 0}`;

  // MOM auto-selection
  const mom = enrichment.fixturePlayers?.length
    ? findMOM(enrichment.fixturePlayers)
    : null;
  const momLine = mom
    ? `Man of the Match (highest rating): ${mom.playerName} (${mom.teamName}) — Rating: ${mom.rating}, Goals: ${mom.goals}, Assists: ${mom.assists}, Shots on target: ${mom.shotsOnTarget}`
    : "MOM data not available.";

  // Match statistics summary
  const statsLines: string[] = [];
  if (md.statistics?.length) {
    for (const s of md.statistics) {
      statsLines.push(`${s.type}: Home=${s.home} Away=${s.away}`);
    }
  }
  const statsBlock = statsLines.length
    ? statsLines.join("\n")
    : "Match statistics not available.";

  // Timeline events
  const eventLines: string[] = [];
  if (md.events?.length) {
    for (const e of (md as MatchDetail).events) {
      if (e.type === "goal") eventLines.push(`${e.minute}' GOAL — ${e.playerName} (${e.assistName ? `assist: ${e.assistName}` : "no assist"})`);
      else if (e.type === "red-card") eventLines.push(`${e.minute}' RED CARD — ${e.playerName}`);
    }
  }
  const eventsBlock = eventLines.length ? eventLines.join("\n") : "No key events recorded.";

  return `You are a professional football analyst. Write a data-driven match recap.
${lang}
Return ONLY a valid JSON object matching this schema — no markdown, no extra text:
${JSON_SCHEMA}

Match data:
- Home: ${home} ${score} ${away}
- Date: ${fixture.date}
- League: ${fixture.leagueSlug}

${momLine}

Match statistics:
${statsBlock}

Key events:
${eventsBlock}

Rules:
- This is a recap — omit the "prediction" field entirely
- Use the MOM data and statistics above to create factual analysis
- insight must have 4–6 paragraphs (\\n\\n separated), reference the MOM and key stats
- keyFactors: exactly 3 items — first item MUST be the MOM if available (icon: "⭐")
- tips: 0 items (empty array)
- Do NOT mention gambling or betting`;
}

async function callClaude(prompt: string): Promise<string | null> {
  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": process.env.ANTHROPIC_API_KEY ?? "",
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: "claude-opus-4-6",
        max_tokens: 2048,
        messages: [{ role: "user", content: prompt }],
      }),
    });
    if (!res.ok) throw new Error(`Claude API ${res.status}`);
    const json = await res.json();
    return json.content?.[0]?.text ?? null;
  } catch (err) {
    console.error("[ai-analysis] Claude API error:", err);
    return null;
  }
}

// ─── Main export ──────────────────────────────────────────────────────────────

export async function generateMatchAnalysis(
  input: AnalysisGenerateInput
): Promise<MatchAnalysis> {
  const { fixture, type, locale = "en" } = input;

  if (isAiMockMode) {
    return getMockAnalysis(input);
  }

  const prompt = buildPrompt(input);
  const text = await callClaude(prompt);

  if (!text) return getMockAnalysis(input);

  // Parse JSON returned by Claude
  let parsed: {
    title?: string;
    summary?: string;
    insight?: string;
    prediction?: AnalysisPrediction;
    keyFactors?: AnalysisKeyFactor[];
    tips?: AnalysisTip[];
  };
  try {
    // Strip potential markdown code fences
    const cleaned = text.replace(/^```(?:json)?\n?/m, "").replace(/\n?```$/m, "").trim();
    parsed = JSON.parse(cleaned);
  } catch {
    console.error("[ai-analysis] JSON parse failed, falling back to mock");
    return getMockAnalysis(input);
  }

  const home = fixture.homeTeam.name;
  const away = fixture.awayTeam.name;
  const fallbackTitle =
    type === "preview"
      ? `${home} vs ${away} Match Preview`
      : `${home} vs ${away} Recap`;

  const title = parsed.title ?? fallbackTitle;
  const isKo = locale === "ko";

  return {
    id: `ai-${fixture.id}-${type}-${locale}-${Date.now()}`,
    fixtureId: fixture.id,
    type,
    locale,
    title,
    slug: buildSlug(home, away, fixture.date, type),
    summary: parsed.summary ?? "",
    insight: parsed.insight ?? "",
    prediction: type === "preview" ? (parsed.prediction ?? undefined) : undefined,
    keyFactors: parsed.keyFactors ?? [],
    tips: parsed.tips ?? [],
    aiModel: "claude-opus-4-6",
    generatedAt: new Date().toISOString(),
    disclaimer: isKo
      ? "AI 분석은 오락 목적으로만 제공됩니다. 과거 성과는 미래 결과를 보장하지 않습니다."
      : "AI predictions are for entertainment purposes only. Past performance does not guarantee future results.",
    isAiGenerated: true,
  };
}
