/**
 * AI Match Analysis Generation
 *
 * Env vars:
 *   ANTHROPIC_API_KEY – Claude API key (optional)
 *   AI_MOCK_MODE      – "true" to use mock analysis
 *
 * Generates match previews and recaps from structured data only.
 * Never hallucinate facts. Only use provided match data.
 */

import type { Fixture, MatchDetail } from "./football/types";

export type AnalysisLocale = "en" | "ko";

export interface AnalysisPrediction {
  outcome: "home" | "away" | "draw";
  label: string;
  confidence: number; // 0-100
}

export interface AnalysisTip {
  label: string;
  labelKo: string;
}

export interface MatchAnalysis {
  id: string;
  fixtureId: number;
  type: "preview" | "recap";
  locale: AnalysisLocale;
  title: string;
  slug: string;
  summary: string;
  insight: string;
  prediction?: AnalysisPrediction;
  tips: AnalysisTip[];
  aiModel: string;
  generatedAt: string;
  disclaimer: string;
  isAiGenerated: boolean;
}

export interface AnalysisGenerateInput {
  fixture: Fixture | MatchDetail;
  type: "preview" | "recap";
  locale?: AnalysisLocale;
}

const AI_MOCK_MODE = process.env.AI_MOCK_MODE === "true" || !process.env.ANTHROPIC_API_KEY;

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function buildPreviewPrompt(fixture: Fixture, locale: AnalysisLocale): string {
  const isKo = locale === "ko";
  return isKo
    ? `다음 경기 데이터를 바탕으로 경기 프리뷰를 작성해주세요. 제공된 데이터만 사용하세요.\n경기: ${fixture.homeTeam.name} vs ${fixture.awayTeam.name}\n날짜: ${fixture.date}\n대회: ${fixture.leagueSlug}`
    : `Write a match preview for the following fixture using only the provided data.\nFixture: ${fixture.homeTeam.name} vs ${fixture.awayTeam.name}\nDate: ${fixture.date}\nCompetition: ${fixture.leagueSlug}`;
}

function buildRecapPrompt(fixture: MatchDetail, locale: AnalysisLocale): string {
  const isKo = locale === "ko";
  const score = `${fixture.homeScore ?? 0}-${fixture.awayScore ?? 0}`;
  return isKo
    ? `다음 경기 결과를 바탕으로 경기 리캡을 작성해주세요.\n경기: ${fixture.homeTeam.name} ${score} ${fixture.awayTeam.name}`
    : `Write a match recap based on the following result.\nFixture: ${fixture.homeTeam.name} ${score} ${fixture.awayTeam.name}`;
}

function getMockAnalysis(input: AnalysisGenerateInput): MatchAnalysis {
  const { fixture, type, locale = "en" } = input;
  const isKo = locale === "ko";
  const homeTeam = fixture.homeTeam.name;
  const awayTeam = fixture.awayTeam.name;
  const title =
    type === "preview"
      ? isKo
        ? `${homeTeam} vs ${awayTeam} 경기 프리뷰`
        : `${homeTeam} vs ${awayTeam} Match Preview`
      : isKo
        ? `${homeTeam} vs ${awayTeam} 경기 결과`
        : `${homeTeam} vs ${awayTeam} Match Recap`;

  return {
    id: `mock-${fixture.id}-${type}-${locale}`,
    fixtureId: fixture.id,
    type,
    locale,
    title,
    slug: slugify(title),
    summary: isKo
      ? `이 분석은 KickVista AI가 구조화된 경기 데이터를 기반으로 생성한 예시 분석입니다.`
      : `This is a sample analysis generated by KickVista AI based on structured match data.`,
    insight: isKo
      ? `최근 맞대결 기록과 홈/원정 폼을 바탕으로 분석한 결과, 이 경기는 팽팽한 접전이 예상됩니다.`
      : `Based on recent head-to-head records and home/away form, this match is expected to be closely contested.`,
    prediction: {
      outcome: "home",
      label: isKo ? "홈 팀 승리" : "Home Win",
      confidence: 58,
    },
    tips: [
      { label: "Both Teams to Score", labelKo: "양팀 득점" },
      { label: "Over 2.5 Goals", labelKo: "2.5골 오버" },
    ],
    aiModel: "KickVista AI (Mock)",
    generatedAt: new Date().toISOString(),
    disclaimer: isKo
      ? "AI 분석은 오락 목적으로만 제공됩니다. 과거 성과는 미래 결과를 보장하지 않습니다."
      : "AI predictions are for entertainment purposes only. Past performance does not guarantee future results.",
    isAiGenerated: true,
  };
}

async function callClaudeAPI(prompt: string): Promise<string | null> {
  if (AI_MOCK_MODE) return null;
  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": process.env.ANTHROPIC_API_KEY ?? "",
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: "claude-opus-4-6",
        max_tokens: 1024,
        messages: [{ role: "user", content: prompt }],
      }),
    });
    if (!res.ok) throw new Error(`Claude API error ${res.status}`);
    const json = await res.json();
    return json.content?.[0]?.text ?? null;
  } catch (err) {
    console.error("[ai-analysis] Claude API error:", err);
    return null;
  }
}

export async function generateMatchAnalysis(
  input: AnalysisGenerateInput
): Promise<MatchAnalysis> {
  const { fixture, type, locale = "en" } = input;

  if (AI_MOCK_MODE) {
    return getMockAnalysis(input);
  }

  const prompt =
    type === "preview"
      ? buildPreviewPrompt(fixture, locale)
      : buildRecapPrompt(fixture as MatchDetail, locale);

  const text = await callClaudeAPI(prompt);
  if (!text) return getMockAnalysis(input);

  const homeTeam = fixture.homeTeam.name;
  const awayTeam = fixture.awayTeam.name;
  const title =
    type === "preview"
      ? `${homeTeam} vs ${awayTeam} Match Preview`
      : `${homeTeam} vs ${awayTeam} Recap`;

  return {
    id: `ai-${fixture.id}-${type}-${locale}-${Date.now()}`,
    fixtureId: fixture.id,
    type,
    locale,
    title,
    slug: slugify(title),
    summary: text.slice(0, 200),
    insight: text,
    aiModel: "claude-opus-4-6",
    generatedAt: new Date().toISOString(),
    tips: [],
    disclaimer:
      locale === "ko"
        ? "AI 분석은 오락 목적으로만 제공됩니다."
        : "AI predictions are for entertainment purposes only.",
    isAiGenerated: true,
  };
}

export const isAiMockMode = AI_MOCK_MODE;

// Mock analysis list for homepage/listing pages
export const MOCK_ANALYSIS_LIST: MatchAnalysis[] = [
  getMockAnalysis({
    fixture: {
      id: 1001,
      leagueId: 39,
      leagueSlug: "premier-league",
      season: 2024,
      round: "Matchday 28",
      date: new Date().toISOString(),
      status: "NS",
      homeTeam: { id: 42, name: "Arsenal", shortName: "ARS", flag: "🔴" },
      awayTeam: { id: 50, name: "Man City", shortName: "MCI", flag: "🔵" },
    },
    type: "preview",
    locale: "en",
  }),
  getMockAnalysis({
    fixture: {
      id: 1002,
      leagueId: 140,
      leagueSlug: "la-liga",
      season: 2024,
      round: "Matchday 28",
      date: new Date().toISOString(),
      status: "NS",
      homeTeam: { id: 541, name: "Real Madrid", shortName: "RMA", flag: "⚪" },
      awayTeam: { id: 529, name: "Barcelona", shortName: "BAR", flag: "🔵" },
    },
    type: "preview",
    locale: "en",
  }),
  getMockAnalysis({
    fixture: {
      id: 1003,
      leagueId: 78,
      leagueSlug: "bundesliga",
      season: 2024,
      round: "Matchday 26",
      date: new Date(Date.now() - 86400000).toISOString(),
      status: "FT",
      homeTeam: { id: 157, name: "Bayern Munich", shortName: "BAY", flag: "🔴" },
      awayTeam: { id: 165, name: "Borussia Dortmund", shortName: "BVB", flag: "🟡" },
      homeScore: 3,
      awayScore: 1,
    },
    type: "recap",
    locale: "en",
  }),
];
