import type { League, LeagueSlug } from "./types";

/**
 * Returns the current football season year.
 * European seasons run Aug–May: Aug–Dec = current year, Jan–Jul = previous year.
 * e.g. March 2026 → 2025 (the 2025-26 season)
 */
export function currentFootballSeason(): number {
  // European seasons run Aug–May: Jan–Jul → previous year.
  // e.g. March 2026 → 2025 (the 2025-26 season) — correct API parameter.
  const now = new Date();
  return now.getMonth() >= 7 ? now.getFullYear() : now.getFullYear() - 1;
}

const SEASON = currentFootballSeason();

const CDN = "https://media.api-sports.io/football/leagues";

export const SUPPORTED_LEAGUES: League[] = [
  {
    id: 39,
    slug: "premier-league",
    name: "Premier League",
    nameKo: "프리미어리그",
    country: "England",
    countryKo: "잉글랜드",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    logo: `${CDN}/39.png`,
    season: SEASON,
    color: "#9333ea",
    totalRounds: 38,
  },
  {
    id: 140,
    slug: "la-liga",
    name: "La Liga",
    nameKo: "라리가",
    country: "Spain",
    countryKo: "스페인",
    flag: "🇪🇸",
    logo: `${CDN}/140.png`,
    season: SEASON,
    color: "#ef4444",
    totalRounds: 38,
  },
  {
    id: 78,
    slug: "bundesliga",
    name: "Bundesliga",
    nameKo: "분데스리가",
    country: "Germany",
    countryKo: "독일",
    flag: "🇩🇪",
    logo: `${CDN}/78.png`,
    season: SEASON,
    color: "#f59e0b",
    totalRounds: 34,
  },
  {
    id: 135,
    slug: "serie-a",
    name: "Serie A",
    nameKo: "세리에 A",
    country: "Italy",
    countryKo: "이탈리아",
    flag: "🇮🇹",
    logo: `${CDN}/135.png`,
    season: SEASON,
    color: "#3b82f6",
    totalRounds: 38,
  },
  {
    id: 61,
    slug: "ligue-1",
    name: "Ligue 1",
    nameKo: "리그 1",
    country: "France",
    countryKo: "프랑스",
    flag: "🇫🇷",
    logo: `${CDN}/61.png`,
    season: SEASON,
    color: "#06b6d4",
    totalRounds: 34,
  },
  {
    id: 2,
    slug: "champions-league",
    name: "Champions League",
    nameKo: "UEFA 챔피언스리그",
    country: "Europe",
    countryKo: "유럽",
    flag: "🌍",
    logo: `${CDN}/2.png`,
    season: SEASON,
    color: "#059669",
  },
  {
    id: 88,
    slug: "eredivisie",
    name: "Eredivisie",
    nameKo: "에레디비시",
    country: "Netherlands",
    countryKo: "네덜란드",
    flag: "🇳🇱",
    logo: `${CDN}/88.png`,
    season: SEASON,
    color: "#f97316",
    totalRounds: 34,
  },
  {
    id: 94,
    slug: "primeira-liga",
    name: "Primeira Liga",
    nameKo: "프리메이라리가",
    country: "Portugal",
    countryKo: "포르투갈",
    flag: "🇵🇹",
    logo: `${CDN}/94.png`,
    season: SEASON,
    color: "#059669",
    totalRounds: 34,
  },
  {
    id: 307,
    slug: "saudi-pro-league",
    name: "Saudi Pro League",
    nameKo: "사우디 프로리그",
    country: "Saudi Arabia",
    countryKo: "사우디아라비아",
    flag: "🇸🇦",
    logo: `${CDN}/307.png`,
    season: SEASON,
    color: "#064E3B",
    totalRounds: 30,
  },
  {
    id: 253,
    slug: "mls",
    name: "MLS",
    nameKo: "MLS",
    country: "USA",
    countryKo: "미국",
    flag: "🇺🇸",
    logo: `${CDN}/253.png`,
    season: SEASON,
    color: "#1d4ed8",
    totalRounds: 34,
  },
  // ── 추가 리그 ────────────────────────────────────────────────────────────────
  {
    id: 3,
    slug: "europa-league",
    name: "Europa League",
    nameKo: "UEFA 유로파리그",
    country: "Europe",
    countryKo: "유럽",
    flag: "🟠",
    logo: `${CDN}/3.png`,
    season: SEASON,
    color: "#f97316",
  },
  {
    id: 292,
    slug: "k-league-1",
    name: "K League 1",
    nameKo: "K리그1",
    country: "South Korea",
    countryKo: "대한민국",
    flag: "🇰🇷",
    logo: `${CDN}/292.png`,
    season: SEASON,
    color: "#003087",
    totalRounds: 38,
  },
  {
    id: 98,
    slug: "j1-league",
    name: "J1 League",
    nameKo: "J1 리그",
    country: "Japan",
    countryKo: "일본",
    flag: "🇯🇵",
    logo: `${CDN}/98.png`,
    season: SEASON,
    color: "#c92424",
    totalRounds: 34,
  },
  {
    id: 262,
    slug: "liga-mx",
    name: "Liga MX",
    nameKo: "리가 MX",
    country: "Mexico",
    countryKo: "멕시코",
    flag: "🇲🇽",
    logo: `${CDN}/262.png`,
    season: SEASON,
    color: "#006847",
    totalRounds: 17,
  },
  {
    id: 203,
    slug: "super-lig",
    name: "Süper Lig",
    nameKo: "쉬페르 리그",
    country: "Turkey",
    countryKo: "튀르키예",
    flag: "🇹🇷",
    logo: `${CDN}/203.png`,
    season: SEASON,
    color: "#c0392b",
    totalRounds: 38,
  },
  {
    id: 71,
    slug: "brasileirao",
    name: "Brasileirão",
    nameKo: "브라질레이랑",
    country: "Brazil",
    countryKo: "브라질",
    flag: "🇧🇷",
    logo: `${CDN}/71.png`,
    season: SEASON,
    color: "#059669",
    totalRounds: 38,
  },
  {
    id: 179,
    slug: "scottish-premiership",
    name: "Scottish Premiership",
    nameKo: "스코티시 프리미어십",
    country: "Scotland",
    countryKo: "스코틀랜드",
    flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    logo: `${CDN}/179.png`,
    season: SEASON,
    color: "#003380",
    totalRounds: 38,
  },
];

export const LEAGUE_BY_SLUG = SUPPORTED_LEAGUES.reduce<Record<LeagueSlug, League>>(
  (acc, league) => ({ ...acc, [league.slug]: league }),
  {} as Record<LeagueSlug, League>
);

export const LEAGUE_IDS = SUPPORTED_LEAGUES.map((l) => l.id);

export const LIVE_STATUSES: string[] = ["1H", "HT", "2H", "ET", "P"];
export const FINISHED_STATUSES: string[] = ["FT", "AET", "PEN"];
export const UPCOMING_STATUSES: string[] = ["NS", "PST"];
