import type { Fixture, StandingEntry, LeagueSlug } from "./types";

// ---------------------------------------------------------------------------
// Helper team definitions — reused across fixtures and standings
// ---------------------------------------------------------------------------

const TEAMS = {
  // Premier League
  arsenal:        { id: 42,  name: "Arsenal",           nameKo: "아스널",         shortName: "ARS", flag: "🔴" },
  manCity:        { id: 50,  name: "Man City",           nameKo: "맨체스터 시티",   shortName: "MCI", flag: "🔵" },
  liverpool:      { id: 40,  name: "Liverpool",          nameKo: "리버풀",         shortName: "LIV", flag: "🔴" },
  chelsea:        { id: 49,  name: "Chelsea",            nameKo: "첼시",           shortName: "CHE", flag: "🔵" },
  manUtd:         { id: 33,  name: "Man United",         nameKo: "맨체스터 유나이티드", shortName: "MUN", flag: "🔴" },
  tottenham:      { id: 47,  name: "Tottenham",          nameKo: "토트넘",         shortName: "TOT", flag: "⚪" },
  newcastle:      { id: 34,  name: "Newcastle",          nameKo: "뉴캐슬",         shortName: "NEW", flag: "⚫" },
  astonVilla:     { id: 66,  name: "Aston Villa",        nameKo: "아스턴 빌라",    shortName: "AVL", flag: "🟣" },
  // La Liga
  realMadrid:     { id: 541, name: "Real Madrid",        nameKo: "레알 마드리드",  shortName: "RMA", flag: "⚪" },
  barcelona:      { id: 529, name: "Barcelona",          nameKo: "바르셀로나",     shortName: "BAR", flag: "🔵" },
  atletico:       { id: 530, name: "Atletico Madrid",    nameKo: "아틀레티코 마드리드", shortName: "ATM", flag: "🔴" },
  sevilla:        { id: 536, name: "Sevilla",            nameKo: "세비야",         shortName: "SEV", flag: "⚪" },
  realBetis:      { id: 543, name: "Real Betis",         nameKo: "레알 베티스",    shortName: "BET", flag: "🟢" },
  // Bundesliga
  bayernMunich:   { id: 157, name: "Bayern Munich",      nameKo: "바이에른 뮌헨",  shortName: "BAY", flag: "🔴" },
  dortmund:       { id: 165, name: "Borussia Dortmund",  nameKo: "보루시아 도르트문트", shortName: "BVB", flag: "🟡" },
  leverkusen:     { id: 168, name: "Bayer Leverkusen",   nameKo: "바이어 레버쿠젠", shortName: "LEV", flag: "🔴" },
  rbLeipzig:      { id: 173, name: "RB Leipzig",         nameKo: "RB 라이프치히",  shortName: "RBL", flag: "🔵" },
  gladbach:       { id: 163, name: "Borussia M'gladbach", nameKo: "묀헨글라트바흐", shortName: "BMG", flag: "🟢" },
  // Serie A
  interMilan:     { id: 505, name: "Inter Milan",        nameKo: "인터 밀란",      shortName: "INT", flag: "🔵" },
  acMilan:        { id: 489, name: "AC Milan",           nameKo: "AC 밀란",        shortName: "MIL", flag: "🔴" },
  juventus:       { id: 496, name: "Juventus",           nameKo: "유벤투스",       shortName: "JUV", flag: "⚫" },
  napoli:         { id: 492, name: "Napoli",             nameKo: "나폴리",         shortName: "NAP", flag: "🔵" },
  roma:           { id: 497, name: "AS Roma",            nameKo: "AS 로마",        shortName: "ROM", flag: "🔴" },
  // Ligue 1
  psg:            { id: 85,  name: "Paris SG",           nameKo: "파리 생제르맹",  shortName: "PSG", flag: "🔵" },
  monaco:         { id: 91,  name: "Monaco",             nameKo: "모나코",         shortName: "MON", flag: "🔴" },
  marseille:      { id: 81,  name: "Marseille",          nameKo: "마르세유",       shortName: "MAR", flag: "🔵" },
  lyon:           { id: 80,  name: "Lyon",               nameKo: "리옹",           shortName: "LYO", flag: "🔴" },
  // Champions League extras
  benfica:        { id: 211, name: "Benfica",            nameKo: "벤피카",         shortName: "BEN", flag: "🔴" },
  psvEindhoven:   { id: 231, name: "PSV Eindhoven",      nameKo: "PSV 에인트호번", shortName: "PSV", flag: "🔴" },
} as const;

// ---------------------------------------------------------------------------
// MOCK_FIXTURES
// ---------------------------------------------------------------------------

export const MOCK_FIXTURES: Fixture[] = [
  // --- Premier League ---
  {
    id: 1001,
    leagueId: 39,
    leagueSlug: "premier-league",
    season: 2024,
    round: "Matchday 28",
    date: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    venue: "Emirates Stadium",
    status: "NS",
    homeTeam: TEAMS.arsenal,
    awayTeam: TEAMS.manCity,
  },
  {
    id: 1002,
    leagueId: 39,
    leagueSlug: "premier-league",
    season: 2024,
    round: "Matchday 28",
    date: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    venue: "Anfield",
    status: "1H",
    minute: 34,
    homeTeam: TEAMS.liverpool,
    awayTeam: TEAMS.chelsea,
    homeScore: 1,
    awayScore: 0,
    homeScoreHT: undefined,
    awayScoreHT: undefined,
  },
  {
    id: 1003,
    leagueId: 39,
    leagueSlug: "premier-league",
    season: 2024,
    round: "Matchday 27",
    date: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    venue: "Old Trafford",
    status: "FT",
    homeTeam: TEAMS.manUtd,
    awayTeam: TEAMS.tottenham,
    homeScore: 2,
    awayScore: 2,
    homeScoreHT: 1,
    awayScoreHT: 0,
  },
  // --- La Liga ---
  {
    id: 2001,
    leagueId: 140,
    leagueSlug: "la-liga",
    season: 2024,
    round: "Matchday 28",
    date: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    venue: "Santiago Bernabéu",
    status: "NS",
    homeTeam: TEAMS.realMadrid,
    awayTeam: TEAMS.barcelona,
  },
  {
    id: 2002,
    leagueId: 140,
    leagueSlug: "la-liga",
    season: 2024,
    round: "Matchday 27",
    date: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    venue: "Civitas Metropolitano",
    status: "FT",
    homeTeam: TEAMS.atletico,
    awayTeam: TEAMS.sevilla,
    homeScore: 3,
    awayScore: 0,
    homeScoreHT: 1,
    awayScoreHT: 0,
  },
  // --- Bundesliga ---
  {
    id: 3001,
    leagueId: 78,
    leagueSlug: "bundesliga",
    season: 2024,
    round: "Matchday 26",
    date: new Date(Date.now() - 3 * 86400 * 1000).toISOString(),
    venue: "Allianz Arena",
    status: "FT",
    homeTeam: TEAMS.bayernMunich,
    awayTeam: TEAMS.dortmund,
    homeScore: 3,
    awayScore: 1,
    homeScoreHT: 1,
    awayScoreHT: 1,
  },
  {
    id: 3002,
    leagueId: 78,
    leagueSlug: "bundesliga",
    season: 2024,
    round: "Matchday 27",
    date: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    venue: "BayArena",
    status: "2H",
    minute: 67,
    homeTeam: TEAMS.leverkusen,
    awayTeam: TEAMS.rbLeipzig,
    homeScore: 2,
    awayScore: 1,
    homeScoreHT: 1,
    awayScoreHT: 0,
  },
  // --- Serie A ---
  {
    id: 4001,
    leagueId: 135,
    leagueSlug: "serie-a",
    season: 2024,
    round: "Matchday 28",
    date: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
    venue: "San Siro",
    status: "NS",
    homeTeam: TEAMS.interMilan,
    awayTeam: TEAMS.juventus,
  },
  // --- Ligue 1 ---
  {
    id: 5001,
    leagueId: 61,
    leagueSlug: "ligue-1",
    season: 2024,
    round: "Matchday 27",
    date: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    venue: "Parc des Princes",
    status: "FT",
    homeTeam: TEAMS.psg,
    awayTeam: TEAMS.monaco,
    homeScore: 4,
    awayScore: 2,
    homeScoreHT: 2,
    awayScoreHT: 1,
  },
  // --- Champions League ---
  {
    id: 6001,
    leagueId: 2,
    leagueSlug: "champions-league",
    season: 2024,
    round: "Round of 16 - 2nd Leg",
    date: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    venue: "Santiago Bernabéu",
    status: "NS",
    homeTeam: TEAMS.realMadrid,
    awayTeam: TEAMS.manCity,
  },
  {
    id: 6002,
    leagueId: 2,
    leagueSlug: "champions-league",
    season: 2024,
    round: "Round of 16 - 2nd Leg",
    date: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    venue: "Estadio da Luz",
    status: "FT",
    homeTeam: TEAMS.benfica,
    awayTeam: TEAMS.arsenal,
    homeScore: 1,
    awayScore: 2,
    homeScoreHT: 0,
    awayScoreHT: 1,
  },
];

// ---------------------------------------------------------------------------
// MOCK_STANDINGS
// ---------------------------------------------------------------------------

export const MOCK_STANDINGS: Record<LeagueSlug, StandingEntry[]> = {
  "premier-league": [
    {
      rank: 1,
      team: TEAMS.arsenal,
      points: 64,
      played: 28,
      won: 20,
      drawn: 4,
      lost: 4,
      goalsFor: 65,
      goalsAgainst: 28,
      goalDifference: 37,
      form: "WWWDW",
      description: "Champions League",
    },
    {
      rank: 2,
      team: TEAMS.manCity,
      points: 61,
      played: 28,
      won: 19,
      drawn: 4,
      lost: 5,
      goalsFor: 61,
      goalsAgainst: 33,
      goalDifference: 28,
      form: "WWLWW",
      description: "Champions League",
    },
    {
      rank: 3,
      team: TEAMS.liverpool,
      points: 59,
      played: 27,
      won: 18,
      drawn: 5,
      lost: 4,
      goalsFor: 72,
      goalsAgainst: 38,
      goalDifference: 34,
      form: "WDWWW",
      description: "Champions League",
    },
    {
      rank: 4,
      team: TEAMS.astonVilla,
      points: 53,
      played: 28,
      won: 16,
      drawn: 5,
      lost: 7,
      goalsFor: 58,
      goalsAgainst: 44,
      goalDifference: 14,
      form: "WDWLW",
      description: "Champions League",
    },
    {
      rank: 5,
      team: TEAMS.tottenham,
      points: 48,
      played: 28,
      won: 14,
      drawn: 6,
      lost: 8,
      goalsFor: 52,
      goalsAgainst: 46,
      goalDifference: 6,
      form: "WLWDW",
      description: "Europa League",
    },
    {
      rank: 6,
      team: TEAMS.chelsea,
      points: 45,
      played: 28,
      won: 13,
      drawn: 6,
      lost: 9,
      goalsFor: 50,
      goalsAgainst: 47,
      goalDifference: 3,
      form: "DWWLL",
      description: "Europa League",
    },
    {
      rank: 7,
      team: TEAMS.newcastle,
      points: 43,
      played: 28,
      won: 12,
      drawn: 7,
      lost: 9,
      goalsFor: 45,
      goalsAgainst: 40,
      goalDifference: 5,
      form: "DLWWD",
    },
    {
      rank: 8,
      team: TEAMS.manUtd,
      points: 35,
      played: 28,
      won: 9,
      drawn: 8,
      lost: 11,
      goalsFor: 30,
      goalsAgainst: 43,
      goalDifference: -13,
      form: "DLLDW",
    },
  ],

  "la-liga": [
    {
      rank: 1,
      team: TEAMS.realMadrid,
      points: 66,
      played: 28,
      won: 21,
      drawn: 3,
      lost: 4,
      goalsFor: 68,
      goalsAgainst: 29,
      goalDifference: 39,
      form: "WWWWW",
      description: "Champions League",
    },
    {
      rank: 2,
      team: TEAMS.barcelona,
      points: 60,
      played: 28,
      won: 18,
      drawn: 6,
      lost: 4,
      goalsFor: 60,
      goalsAgainst: 34,
      goalDifference: 26,
      form: "DWWWW",
      description: "Champions League",
    },
    {
      rank: 3,
      team: TEAMS.atletico,
      points: 58,
      played: 28,
      won: 17,
      drawn: 7,
      lost: 4,
      goalsFor: 54,
      goalsAgainst: 27,
      goalDifference: 27,
      form: "WWDWW",
      description: "Champions League",
    },
    {
      rank: 4,
      team: TEAMS.realBetis,
      points: 44,
      played: 28,
      won: 13,
      drawn: 5,
      lost: 10,
      goalsFor: 42,
      goalsAgainst: 40,
      goalDifference: 2,
      form: "WLDWL",
      description: "Europa League",
    },
    {
      rank: 5,
      team: TEAMS.sevilla,
      points: 38,
      played: 28,
      won: 10,
      drawn: 8,
      lost: 10,
      goalsFor: 38,
      goalsAgainst: 42,
      goalDifference: -4,
      form: "LWDLW",
    },
  ],

  "bundesliga": [
    {
      rank: 1,
      team: TEAMS.leverkusen,
      points: 68,
      played: 27,
      won: 22,
      drawn: 2,
      lost: 3,
      goalsFor: 72,
      goalsAgainst: 24,
      goalDifference: 48,
      form: "WWWWW",
      description: "Champions League",
    },
    {
      rank: 2,
      team: TEAMS.bayernMunich,
      points: 60,
      played: 27,
      won: 19,
      drawn: 3,
      lost: 5,
      goalsFor: 75,
      goalsAgainst: 36,
      goalDifference: 39,
      form: "WWWLW",
      description: "Champions League",
    },
    {
      rank: 3,
      team: TEAMS.rbLeipzig,
      points: 52,
      played: 27,
      won: 15,
      drawn: 7,
      lost: 5,
      goalsFor: 58,
      goalsAgainst: 38,
      goalDifference: 20,
      form: "DWWWD",
      description: "Champions League",
    },
    {
      rank: 4,
      team: TEAMS.dortmund,
      points: 48,
      played: 27,
      won: 14,
      drawn: 6,
      lost: 7,
      goalsFor: 52,
      goalsAgainst: 44,
      goalDifference: 8,
      form: "LWWDW",
      description: "Europa League",
    },
    {
      rank: 5,
      team: TEAMS.gladbach,
      points: 38,
      played: 27,
      won: 11,
      drawn: 5,
      lost: 11,
      goalsFor: 44,
      goalsAgainst: 50,
      goalDifference: -6,
      form: "WDLWL",
    },
  ],

  "serie-a": [
    {
      rank: 1,
      team: TEAMS.interMilan,
      points: 67,
      played: 28,
      won: 21,
      drawn: 4,
      lost: 3,
      goalsFor: 66,
      goalsAgainst: 22,
      goalDifference: 44,
      form: "WWWWW",
      description: "Champions League",
    },
    {
      rank: 2,
      team: TEAMS.juventus,
      points: 54,
      played: 28,
      won: 16,
      drawn: 6,
      lost: 6,
      goalsFor: 48,
      goalsAgainst: 28,
      goalDifference: 20,
      form: "WDWLW",
      description: "Champions League",
    },
    {
      rank: 3,
      team: TEAMS.acMilan,
      points: 51,
      played: 28,
      won: 15,
      drawn: 6,
      lost: 7,
      goalsFor: 50,
      goalsAgainst: 35,
      goalDifference: 15,
      form: "WWDLW",
      description: "Champions League",
    },
    {
      rank: 4,
      team: TEAMS.napoli,
      points: 47,
      played: 28,
      won: 14,
      drawn: 5,
      lost: 9,
      goalsFor: 52,
      goalsAgainst: 40,
      goalDifference: 12,
      form: "WLWWL",
      description: "Europa League",
    },
    {
      rank: 5,
      team: TEAMS.roma,
      points: 44,
      played: 28,
      won: 13,
      drawn: 5,
      lost: 10,
      goalsFor: 47,
      goalsAgainst: 42,
      goalDifference: 5,
      form: "LDWWW",
      description: "Europa League",
    },
  ],

  "ligue-1": [
    {
      rank: 1,
      team: TEAMS.psg,
      points: 72,
      played: 27,
      won: 23,
      drawn: 3,
      lost: 1,
      goalsFor: 74,
      goalsAgainst: 25,
      goalDifference: 49,
      form: "WWWWW",
      description: "Champions League",
    },
    {
      rank: 2,
      team: TEAMS.monaco,
      points: 55,
      played: 27,
      won: 17,
      drawn: 4,
      lost: 6,
      goalsFor: 56,
      goalsAgainst: 36,
      goalDifference: 20,
      form: "WWLWW",
      description: "Champions League",
    },
    {
      rank: 3,
      team: TEAMS.marseille,
      points: 52,
      played: 27,
      won: 15,
      drawn: 7,
      lost: 5,
      goalsFor: 48,
      goalsAgainst: 32,
      goalDifference: 16,
      form: "WDWDW",
      description: "Champions League",
    },
    {
      rank: 4,
      team: TEAMS.lyon,
      points: 43,
      played: 27,
      won: 12,
      drawn: 7,
      lost: 8,
      goalsFor: 44,
      goalsAgainst: 40,
      goalDifference: 4,
      form: "DLWWL",
      description: "Europa League",
    },
  ],

  "champions-league": [
    {
      rank: 1,
      team: TEAMS.realMadrid,
      points: 18,
      played: 8,
      won: 6,
      drawn: 0,
      lost: 2,
      goalsFor: 20,
      goalsAgainst: 8,
      goalDifference: 12,
      form: "WWWWW",
    },
    {
      rank: 2,
      team: TEAMS.manCity,
      points: 16,
      played: 8,
      won: 5,
      drawn: 1,
      lost: 2,
      goalsFor: 18,
      goalsAgainst: 10,
      goalDifference: 8,
      form: "WWDWW",
    },
    {
      rank: 3,
      team: TEAMS.arsenal,
      points: 15,
      played: 8,
      won: 5,
      drawn: 0,
      lost: 3,
      goalsFor: 15,
      goalsAgainst: 12,
      goalDifference: 3,
      form: "WWWLW",
    },
    {
      rank: 4,
      team: TEAMS.bayernMunich,
      points: 13,
      played: 8,
      won: 4,
      drawn: 1,
      lost: 3,
      goalsFor: 14,
      goalsAgainst: 11,
      goalDifference: 3,
      form: "WLWDW",
    },
    {
      rank: 5,
      team: TEAMS.psvEindhoven,
      points: 12,
      played: 8,
      won: 4,
      drawn: 0,
      lost: 4,
      goalsFor: 12,
      goalsAgainst: 14,
      goalDifference: -2,
      form: "WLWWL",
    },
  ],
};
