import type { Fixture, LineupPlayer } from "@/lib/football/types";

export const MOCK_MATCHES: Record<string, Fixture & {
  events: Array<{
    minute: number;
    type: "goal" | "yellow-card" | "red-card" | "substitution";
    team: "home" | "away";
    player: string;
    assist?: string;
  }>;
  statistics: Array<{ label: string; labelKo: string; home: string | number; away: string | number }>;
  lineupHome: LineupPlayer[];
  lineupAway: LineupPlayer[];
}> = {
  "1": {
    id: 1,
    leagueId: 39,
    leagueSlug: "premier-league",
    season: 2025,
    round: "Round 28",
    date: "2026-03-14T16:00:00Z",
    venue: "Emirates Stadium, London",
    status: "FT",
    homeTeam: { id: 42, name: "Arsenal", nameKo: "아스날", shortName: "ARS", flag: "🔴" },
    awayTeam: { id: 50, name: "Man City", nameKo: "맨시티", shortName: "MCI", flag: "🔵" },
    homeScore: 2,
    awayScore: 1,
    homeScoreHT: 1,
    awayScoreHT: 0,
    events: [
      { minute: 22, type: "goal",        team: "home", player: "Bukayo Saka",      assist: "Martin Ødegaard" },
      { minute: 45, type: "yellow-card", team: "away", player: "Rodri" },
      { minute: 58, type: "goal",        team: "away", player: "Erling Haaland",   assist: "Kevin De Bruyne" },
      { minute: 71, type: "goal",        team: "home", player: "Kai Havertz",      assist: "Bukayo Saka" },
      { minute: 82, type: "red-card",    team: "away", player: "Kyle Walker" },
      { minute: 89, type: "substitution", team: "home", player: "Gabriel Martinelli", assist: "Leandro Trossard" },
    ],
    statistics: [
      { label: "Possession",     labelKo: "점유율",       home: "58%",  away: "42%" },
      { label: "Shots",          labelKo: "슈팅",         home: 14,     away: 9   },
      { label: "Shots on Target",labelKo: "유효슈팅",     home: 7,      away: 4   },
      { label: "Corners",        labelKo: "코너킥",       home: 7,      away: 3   },
      { label: "Fouls",          labelKo: "반칙",         home: 10,     away: 14  },
      { label: "Yellow Cards",   labelKo: "경고",         home: 1,      away: 2   },
      { label: "Red Cards",      labelKo: "퇴장",         home: 0,      away: 1   },
      { label: "Offsides",       labelKo: "오프사이드",   home: 2,      away: 4   },
      { label: "Passes",         labelKo: "패스",         home: 542,    away: 391 },
      { label: "Pass Accuracy",  labelKo: "패스 성공률",  home: "87%",  away: "83%" },
    ],
    lineupHome: [
      { name: "David Raya",              number: 22, pos: "G" },
      { name: "Ben White",               number: 4,  pos: "D" },
      { name: "William Saliba",          number: 12, pos: "D" },
      { name: "Gabriel Magalhães",       number: 6,  pos: "D" },
      { name: "Oleksandr Zinchenko",     number: 35, pos: "D" },
      { name: "Thomas Partey",           number: 5,  pos: "M" },
      { name: "Martin Ødegaard",         number: 8,  pos: "M" },
      { name: "Declan Rice",             number: 41, pos: "M" },
      { name: "Bukayo Saka",             number: 7,  pos: "F" },
      { name: "Gabriel Jesus",           number: 9,  pos: "F" },
      { name: "Leandro Trossard",        number: 19, pos: "F" },
    ],
    lineupAway: [
      { name: "Ederson",                 number: 31, pos: "G" },
      { name: "Kyle Walker",             number: 2,  pos: "D" },
      { name: "Rúben Dias",              number: 3,  pos: "D" },
      { name: "Manuel Akanji",           number: 25, pos: "D" },
      { name: "Josko Gvardiol",          number: 24, pos: "D" },
      { name: "Rodri",                   number: 16, pos: "M" },
      { name: "Kevin De Bruyne",         number: 17, pos: "M" },
      { name: "Bernardo Silva",          number: 20, pos: "M" },
      { name: "Phil Foden",              number: 47, pos: "F" },
      { name: "Jack Grealish",           number: 10, pos: "F" },
      { name: "Erling Haaland",          number: 9,  pos: "F" },
    ],
  },
  "2": {
    id: 2,
    leagueId: 140,
    leagueSlug: "la-liga",
    season: 2025,
    round: "Round 28",
    date: "2026-03-14T19:00:00Z",
    venue: "Santiago Bernabéu, Madrid",
    status: "2H",
    minute: 67,
    homeTeam: { id: 541, name: "Real Madrid", nameKo: "레알 마드리드", shortName: "RMA", flag: "⚪" },
    awayTeam: { id: 529, name: "Barcelona",   nameKo: "FC 바르셀로나",  shortName: "BAR", flag: "🔵" },
    homeScore: 1,
    awayScore: 1,
    homeScoreHT: 1,
    awayScoreHT: 0,
    events: [
      { minute: 34, type: "goal",        team: "home", player: "Vinícius Jr.",   assist: "Jude Bellingham" },
      { minute: 52, type: "goal",        team: "away", player: "Robert Lewandowski", assist: "Pedri" },
      { minute: 60, type: "yellow-card", team: "home", player: "Aurélien Tchouaméni" },
    ],
    statistics: [
      { label: "Possession",     labelKo: "점유율",       home: "47%",  away: "53%" },
      { label: "Shots",          labelKo: "슈팅",         home: 8,      away: 10  },
      { label: "Shots on Target",labelKo: "유효슈팅",     home: 4,      away: 5   },
      { label: "Corners",        labelKo: "코너킥",       home: 4,      away: 6   },
      { label: "Fouls",          labelKo: "반칙",         home: 12,     away: 9   },
      { label: "Yellow Cards",   labelKo: "경고",         home: 1,      away: 0   },
      { label: "Passes",         labelKo: "패스",         home: 380,    away: 440 },
      { label: "Pass Accuracy",  labelKo: "패스 성공률",  home: "81%",  away: "89%" },
    ],
    lineupHome: [
      { name: "Thibaut Courtois",        number: 1,  pos: "G" },
      { name: "Dani Carvajal",           number: 2,  pos: "D" },
      { name: "Éder Militão",            number: 3,  pos: "D" },
      { name: "Antonio Rüdiger",         number: 22, pos: "D" },
      { name: "Ferland Mendy",           number: 23, pos: "D" },
      { name: "Aurélien Tchouaméni",     number: 18, pos: "M" },
      { name: "Eduardo Camavinga",       number: 12, pos: "M" },
      { name: "Jude Bellingham",         number: 5,  pos: "M" },
      { name: "Federico Valverde",       number: 8,  pos: "F" },
      { name: "Rodrygo",                 number: 11, pos: "F" },
      { name: "Vinícius Jr.",            number: 7,  pos: "F" },
    ],
    lineupAway: [
      { name: "Marc-André ter Stegen",   number: 1,  pos: "G" },
      { name: "Jules Koundé",            number: 23, pos: "D" },
      { name: "Ronald Araújo",           number: 4,  pos: "D" },
      { name: "Andreas Christensen",     number: 15, pos: "D" },
      { name: "Alejandro Balde",         number: 3,  pos: "D" },
      { name: "Pedri",                   number: 8,  pos: "M" },
      { name: "Frenkie de Jong",         number: 21, pos: "M" },
      { name: "Gavi",                    number: 6,  pos: "M" },
      { name: "Lamine Yamal",            number: 27, pos: "F" },
      { name: "Raphinha",                number: 11, pos: "F" },
      { name: "Robert Lewandowski",      number: 9,  pos: "F" },
    ],
  },
};
