import type { Fixture, LineupPlayer, StandingEntry, LeagueSlug } from "./types";

/** Shorthand to build a LineupPlayer from name + jersey number + API pos code */
function p(name: string, number: number, pos: "G" | "D" | "M" | "F"): LineupPlayer {
  return { name, number, pos };
}

// ---------------------------------------------------------------------------
// Helper team definitions — reused across fixtures and standings
// ---------------------------------------------------------------------------

const TEAMS = {
  // Premier League
  arsenal:        { id: 42,  name: "Arsenal",           nameKo: "아스널",         shortName: "ARS", flag: "🔴" },
  manCity:        { id: 50,  name: "Man City",           nameKo: "맨체스터 시티",   shortName: "MCI", flag: "🔵" },
  liverpool:      { id: 40,  name: "Liverpool",          nameKo: "리버풀",         shortName: "LIV", flag: "🔴" },
  chelsea:        { id: 49,  name: "Chelsea",            nameKo: "첼시",           shortName: "CHE", flag: "🔵" },
  manUtd:         { id: 33,  name: "Man United",         nameKo: "맨체스터 유나이티드", shortName: "MUN", flag: "🔴" },
  tottenham:      { id: 47,  name: "Tottenham",          nameKo: "토트넘",         shortName: "TOT", flag: "⚪" },
  newcastle:      { id: 34,  name: "Newcastle",          nameKo: "뉴캐슬",         shortName: "NEW", flag: "⚫" },
  astonVilla:     { id: 66,  name: "Aston Villa",        nameKo: "아스턴 빌라",    shortName: "AVL", flag: "🟣" },
  // La Liga
  realMadrid:     { id: 541, name: "Real Madrid",        nameKo: "레알 마드리드",  shortName: "RMA", flag: "⚪" },
  barcelona:      { id: 529, name: "Barcelona",          nameKo: "바르셀로나",     shortName: "BAR", flag: "🔵" },
  atletico:       { id: 530, name: "Atletico Madrid",    nameKo: "아틀레티코 마드리드", shortName: "ATM", flag: "🔴" },
  sevilla:        { id: 536, name: "Sevilla",            nameKo: "세비야",         shortName: "SEV", flag: "⚪" },
  realBetis:      { id: 543, name: "Real Betis",         nameKo: "레알 베티스",    shortName: "BET", flag: "🟢" },
  // Bundesliga
  bayernMunich:   { id: 157, name: "Bayern Munich",      nameKo: "바이에른 뮌헨",  shortName: "BAY", flag: "🔴" },
  dortmund:       { id: 165, name: "Borussia Dortmund",  nameKo: "보루시아 도르트문트", shortName: "BVB", flag: "🟡" },
  leverkusen:     { id: 168, name: "Bayer Leverkusen",   nameKo: "바이어 레버쿠젠", shortName: "LEV", flag: "🔴" },
  rbLeipzig:      { id: 173, name: "RB Leipzig",         nameKo: "RB 라이프치히",  shortName: "RBL", flag: "🔵" },
  gladbach:       { id: 163, name: "Borussia M'gladbach", nameKo: "묀헨글라트바흐", shortName: "BMG", flag: "🟢" },
  // Serie A
  interMilan:     { id: 505, name: "Inter Milan",        nameKo: "인터 밀란",      shortName: "INT", flag: "🔵" },
  acMilan:        { id: 489, name: "AC Milan",           nameKo: "AC 밀란",        shortName: "MIL", flag: "🔴" },
  juventus:       { id: 496, name: "Juventus",           nameKo: "유벤투스",       shortName: "JUV", flag: "⚫" },
  napoli:         { id: 492, name: "Napoli",             nameKo: "나폴리",         shortName: "NAP", flag: "🔵" },
  roma:           { id: 497, name: "AS Roma",            nameKo: "AS 로마",        shortName: "ROM", flag: "🔴" },
  // Ligue 1
  psg:            { id: 85,  name: "Paris SG",           nameKo: "파리 생제르맹",  shortName: "PSG", flag: "🔵" },
  monaco:         { id: 91,  name: "Monaco",             nameKo: "모나코",         shortName: "MON", flag: "🔴" },
  marseille:      { id: 81,  name: "Marseille",          nameKo: "마르세유",       shortName: "MAR", flag: "🔵" },
  lyon:           { id: 80,  name: "Lyon",               nameKo: "리옹",           shortName: "LYO", flag: "🔴" },
  // Champions League extras
  benfica:        { id: 211, name: "Benfica",            nameKo: "벤피카",         shortName: "BEN", flag: "🔴" },
  psvEindhoven:   { id: 231, name: "PSV Eindhoven",      nameKo: "PSV 에인트호번", shortName: "PSV", flag: "🔴" },
  // More Premier League
  brighton:        { id: 51,   name: "Brighton",          nameKo: "브라이턴",         shortName: "BHA", flag: "🔵" },
  westHam:         { id: 48,   name: "West Ham",           nameKo: "웨스트 햄",         shortName: "WHU", flag: "🟣" },
  wolves:          { id: 39,   name: "Wolves",             nameKo: "울버햄튼",          shortName: "WOL", flag: "🟡" },
  fulham:          { id: 36,   name: "Fulham",             nameKo: "풀럼",              shortName: "FUL", flag: "⚪" },
  brentford:       { id: 55,   name: "Brentford",          nameKo: "브렌트퍼드",        shortName: "BRE", flag: "🔴" },
  crystalPalace:   { id: 52,   name: "Crystal Palace",     nameKo: "크리스탈 팰리스",   shortName: "CRY", flag: "🔴" },
  everton:         { id: 45,   name: "Everton",            nameKo: "에버턴",            shortName: "EVE", flag: "🔵" },
  nottmForest:     { id: 65,   name: "Nottm Forest",       nameKo: "노팅엄 포레스트",   shortName: "NFO", flag: "🔴" },
  bournemouth:     { id: 35,   name: "Bournemouth",        nameKo: "본머스",            shortName: "BOU", flag: "🔴" },
  luton:           { id: 1359, name: "Luton",              nameKo: "루턴",              shortName: "LUT", flag: "🟠" },
  burnley:         { id: 44,   name: "Burnley",            nameKo: "번리",              shortName: "BUR", flag: "🟣" },
  sheffield:       { id: 62,   name: "Sheffield Utd",      nameKo: "셰필드 유나이티드", shortName: "SHU", flag: "🔴" },
  // More La Liga
  realSociedad:    { id: 548,  name: "Real Sociedad",      nameKo: "레알 소시에다드",   shortName: "RSO", flag: "🔵" },
  athleticBilbao:  { id: 531,  name: "Athletic Bilbao",    nameKo: "아틀레틱 빌바오",   shortName: "ATH", flag: "🔴" },
  valencia:        { id: 532,  name: "Valencia",           nameKo: "발렌시아",          shortName: "VAL", flag: "⚪" },
  villarreal:      { id: 533,  name: "Villarreal",         nameKo: "비야레알",          shortName: "VIL", flag: "🟡" },
  girona:          { id: 547,  name: "Girona",             nameKo: "지로나",            shortName: "GIR", flag: "🔴" },
  osasuna:         { id: 727,  name: "Osasuna",            nameKo: "오사수나",          shortName: "OSA", flag: "🔴" },
  getafe:          { id: 546,  name: "Getafe",             nameKo: "헤타페",            shortName: "GET", flag: "🔵" },
  celtaVigo:       { id: 538,  name: "Celta Vigo",         nameKo: "셀타 비고",         shortName: "CEL", flag: "🔵" },
  cadiz:           { id: 724,  name: "Cádiz",              nameKo: "카디스",            shortName: "CAD", flag: "🟡" },
  rayo:            { id: 728,  name: "Rayo Vallecano",     nameKo: "라요 바예카노",      shortName: "RAY", flag: "🔴" },
  alaves:          { id: 542,  name: "Alaves",             nameKo: "알라베스",          shortName: "ALA", flag: "🔵" },
  almeria:         { id: 723,  name: "Almería",            nameKo: "알메리아",          shortName: "ALM", flag: "🔴" },
  mallorca:        { id: 798,  name: "Mallorca",           nameKo: "마요르카",          shortName: "MLL", flag: "🔴" },
  lasPalmas:       { id: 534,  name: "Las Palmas",         nameKo: "라스 팔마스",       shortName: "LPA", flag: "🟡" },
  // More Bundesliga
  frankfurt:       { id: 169,  name: "Eintracht Frankfurt",nameKo: "아인트라흐트 프랑크푸르트", shortName: "SGE", flag: "🔴" },
  freiburg:        { id: 160,  name: "Freiburg",           nameKo: "프라이부르크",       shortName: "SCF", flag: "🔴" },
  wolfsburg:       { id: 161,  name: "Wolfsburg",          nameKo: "볼프스부르크",       shortName: "WOB", flag: "🟢" },
  stuttgart:       { id: 172,  name: "Stuttgart",          nameKo: "슈투트가르트",       shortName: "VFB", flag: "🔴" },
  augsburg:        { id: 170,  name: "Augsburg",           nameKo: "아우크스부르크",     shortName: "FCA", flag: "🔴" },
  unionBerlin:     { id: 182,  name: "Union Berlin",       nameKo: "우니온 베를린",      shortName: "FCU", flag: "🔴" },
  mainz:           { id: 164,  name: "Mainz",              nameKo: "마인츠",             shortName: "M05", flag: "🔴" },
  hoffenheim:      { id: 167,  name: "Hoffenheim",         nameKo: "호펜하임",           shortName: "TSG", flag: "🔵" },
  heidenheim:      { id: 180,  name: "Heidenheim",         nameKo: "하이덴하임",         shortName: "FCH", flag: "🔴" },
  cologne:         { id: 192,  name: "Cologne",            nameKo: "쾰른",               shortName: "KOE", flag: "⚪" },
  werder:          { id: 162,  name: "Werder Bremen",      nameKo: "베르더 브레멘",      shortName: "SVW", flag: "🟢" },
  darmstadt:       { id: 176,  name: "Darmstadt",          nameKo: "다름슈타트",         shortName: "D98", flag: "🔵" },
  bochum:          { id: 171,  name: "Bochum",             nameKo: "보훔",               shortName: "BOC", flag: "🔵" },
  // More Serie A
  atalanta:        { id: 499,  name: "Atalanta",           nameKo: "아탈란타",           shortName: "ATL", flag: "🔵" },
  fiorentina:      { id: 502,  name: "Fiorentina",         nameKo: "피오렌티나",         shortName: "FIO", flag: "🟣" },
  lazio:           { id: 487,  name: "Lazio",              nameKo: "라치오",             shortName: "LAZ", flag: "🔵" },
  bologna:         { id: 500,  name: "Bologna",            nameKo: "볼로냐",             shortName: "BOL", flag: "🔴" },
  torino:          { id: 503,  name: "Torino",             nameKo: "토리노",             shortName: "TOR", flag: "🟣" },
  monza:           { id: 1579, name: "Monza",              nameKo: "몬차",               shortName: "MON", flag: "🔴" },
  genoa:           { id: 495,  name: "Genoa",              nameKo: "제노아",             shortName: "GEN", flag: "🔴" },
  udinese:         { id: 494,  name: "Udinese",            nameKo: "우디네세",           shortName: "UDI", flag: "⚫" },
  lecce:           { id: 867,  name: "Lecce",              nameKo: "레체",               shortName: "LEC", flag: "🔴" },
  frosinone:       { id: 511,  name: "Frosinone",          nameKo: "프로지노네",         shortName: "FRO", flag: "🟡" },
  cagliari:        { id: 490,  name: "Cagliari",           nameKo: "칼리아리",           shortName: "CAG", flag: "🔴" },
  empoli:          { id: 508,  name: "Empoli",             nameKo: "엠폴리",             shortName: "EMP", flag: "🔵" },
  salernitana:     { id: 514,  name: "Salernitana",        nameKo: "살레르니타나",       shortName: "SAL", flag: "🔴" },
  sassulo:         { id: 488,  name: "Sassuolo",           nameKo: "사수올로",           shortName: "SAS", flag: "🟢" },
  hellas:          { id: 504,  name: "Hellas Verona",      nameKo: "엘라스 베로나",      shortName: "HEL", flag: "🟡" },
  // More Ligue 1
  lille:           { id: 79,   name: "Lille",              nameKo: "릴",                 shortName: "LIL", flag: "🔴" },
  nice:            { id: 84,   name: "Nice",               nameKo: "니스",               shortName: "NIC", flag: "🔴" },
  rennes:          { id: 94,   name: "Rennes",             nameKo: "렌",                 shortName: "REN", flag: "🔴" },
  lens:            { id: 116,  name: "Lens",               nameKo: "랑스",               shortName: "RCL", flag: "🟡" },
  strasbourg:      { id: 95,   name: "Strasbourg",         nameKo: "스트라스부르",       shortName: "STR", flag: "🔵" },
  montpellier:     { id: 82,   name: "Montpellier",        nameKo: "몽펠리에",           shortName: "MTP", flag: "🟠" },
  toulouse:        { id: 96,   name: "Toulouse",           nameKo: "툴루즈",             shortName: "TOU", flag: "🟣" },
  reims:           { id: 93,   name: "Reims",              nameKo: "랭스",               shortName: "REI", flag: "🔴" },
  nantes:          { id: 83,   name: "Nantes",             nameKo: "낭트",               shortName: "NAN", flag: "🟡" },
  brest:           { id: 130,  name: "Brest",              nameKo: "브레스트",           shortName: "BRS", flag: "🔴" },
  lorient:         { id: 114,  name: "Lorient",            nameKo: "로리앙",             shortName: "LOR", flag: "🟠" },
  leHavre:         { id: 119,  name: "Le Havre",           nameKo: "르아브르",           shortName: "HAC", flag: "🔵" },
  metz:            { id: 92,   name: "Metz",               nameKo: "메스",               shortName: "MET", flag: "🔴" },
  clermont:        { id: 523,  name: "Clermont",           nameKo: "클레르몽",           shortName: "CF63",flag: "🔴" },
  // Eredivisie
  ajax:            { id: 194,  name: "Ajax",               nameKo: "아약스",             shortName: "AJA", flag: "🔴" },
  feyenoord:       { id: 197,  name: "Feyenoord",          nameKo: "페예노르트",         shortName: "FEY", flag: "🔴" },
  azAlkmaar:       { id: 193,  name: "AZ Alkmaar",         nameKo: "AZ 알크마르",        shortName: "AZA", flag: "🔴" },
  twente:          { id: 198,  name: "Twente",             nameKo: "트벤터",             shortName: "TWE", flag: "🔴" },
  psv:             { id: 231,  name: "PSV",                nameKo: "PSV",                shortName: "PSV", flag: "🔴" },
  utrechtTeam:     { id: 200,  name: "Utrecht",            nameKo: "위트레흐트",         shortName: "UTR", flag: "🔴" },
  heerenveen:      { id: 196,  name: "Heerenveen",         nameKo: "헤이런베인",         shortName: "HEE", flag: "🔵" },
  groningen:       { id: 204,  name: "Groningen",          nameKo: "흐로닝언",           shortName: "GRO", flag: "🟢" },
  // Primeira Liga
  porto:           { id: 212,  name: "Porto",              nameKo: "포르투",             shortName: "POR", flag: "🔵" },
  portoBenfica:    { id: 211,  name: "Benfica",            nameKo: "벤피카",             shortName: "BEN", flag: "🔴" },
  sporting:        { id: 228,  name: "Sporting CP",        nameKo: "스포르팅 CP",        shortName: "SPO", flag: "🟢" },
  braga:           { id: 217,  name: "Braga",              nameKo: "브라가",             shortName: "BRA", flag: "🔴" },
  vitoria:         { id: 227,  name: "Vitória SC",         nameKo: "비토리아 SC",        shortName: "VIT", flag: "🟢" },
  guimaraes:       { id: 232,  name: "V. Guimarães",       nameKo: "V. 기마랑이스",      shortName: "VGI", flag: "🔵" },
  farense:         { id: 213,  name: "Farense",            nameKo: "파렌시",             shortName: "FAR", flag: "🔴" },
  aves:            { id: 225,  name: "Aves",               nameKo: "아베스",             shortName: "AVE", flag: "🔴" },
  // Saudi Pro League
  alHilal:         { id: 2912, name: "Al-Hilal",           nameKo: "알 힐랄",            shortName: "HIL", flag: "🔵" },
  alNassr:         { id: 2913, name: "Al-Nassr",           nameKo: "알 나스르",          shortName: "NAS", flag: "🟡" },
  alIttihad:       { id: 2921, name: "Al-Ittihad",         nameKo: "알 이티하드",        shortName: "ITT", flag: "🟡" },
  alAhli:          { id: 2914, name: "Al-Ahli",            nameKo: "알 아흘리",          shortName: "AHL", flag: "🟢" },
  alQadsiah:       { id: 2917, name: "Al-Qadsiah",         nameKo: "알 카디시아",        shortName: "QAD", flag: "🔵" },
  alFaisaly:       { id: 2916, name: "Al-Faisaly",         nameKo: "알 파이살리",        shortName: "FAI", flag: "🟢" },
  alShabbab:       { id: 2918, name: "Al-Shabbab",         nameKo: "알 샤밥",            shortName: "SHA", flag: "🔴" },
  alTaawoun:       { id: 2919, name: "Al-Taawoun",         nameKo: "알 타아원",          shortName: "TAA", flag: "🟡" },
  // MLS
  interMiami:      { id: 1602, name: "Inter Miami",        nameKo: "인터 마이애미",      shortName: "MIA", flag: "🩷" },
  laGalaxy:        { id: 1611, name: "LA Galaxy",          nameKo: "LA 갤럭시",          shortName: "LAG", flag: "🔵" },
  nycfc:           { id: 1605, name: "NYC FC",             nameKo: "뉴욕 시티 FC",       shortName: "NYC", flag: "🔵" },
  seattle:         { id: 1614, name: "Seattle Sounders",   nameKo: "시애틀 사운더스",    shortName: "SEA", flag: "🟢" },
  portland:        { id: 1615, name: "Portland Timbers",   nameKo: "포틀랜드 팀버스",    shortName: "PTB", flag: "🟢" },
  atlAtlanta:      { id: 1601, name: "Atlanta United",     nameKo: "애틀랜타 유나이티드", shortName: "ATU", flag: "🔴" },
  chicagoFire:     { id: 1607, name: "Chicago Fire",       nameKo: "시카고 파이어",      shortName: "CHI", flag: "🔴" },
  nycRB:           { id: 1608, name: "NY Red Bulls",       nameKo: "뉴욕 레드불스",      shortName: "NYR", flag: "🔴" },
} as const;

// Attach CDN logo URL to every mock team entry (avoids repeating the URL 80+ times).
const CDN = "https://media.api-sports.io/football/teams";
type RawTeam = (typeof TEAMS)[keyof typeof TEAMS];
type TeamWithLogo = RawTeam & { logo: string };
const T = Object.fromEntries(
  Object.entries(TEAMS).map(([k, v]) => [k, { ...v, logo: `${CDN}/${v.id}.png` }])
) as { [K in keyof typeof TEAMS]: TeamWithLogo };

// ---------------------------------------------------------------------------
// MOCK_FIXTURES
// ---------------------------------------------------------------------------

export const MOCK_FIXTURES: Fixture[] = [
  // --- Premier League ---
  {
    id: 1001,
    leagueId: 39,
    leagueSlug: "premier-league",
    season: 2025,
    round: "Matchday 28",
    date: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    venue: "Emirates Stadium",
    status: "NS",
    homeTeam: T.arsenal,
    awayTeam: T.manCity,
    lineupHome: [p("David Raya",22,"G"),p("Ben White",4,"D"),p("William Saliba",12,"D"),p("Gabriel Magalhães",6,"D"),p("Oleksandr Zinchenko",35,"D"),p("Thomas Partey",5,"M"),p("Martin Ødegaard",8,"M"),p("Declan Rice",41,"M"),p("Bukayo Saka",7,"F"),p("Gabriel Jesus",9,"F"),p("Leandro Trossard",19,"F")],
    lineupAway: [p("Ederson",31,"G"),p("Kyle Walker",2,"D"),p("Rúben Dias",3,"D"),p("Manuel Akanji",25,"D"),p("Josko Gvardiol",24,"D"),p("Rodri",16,"M"),p("Kevin De Bruyne",17,"M"),p("Bernardo Silva",20,"M"),p("Phil Foden",47,"F"),p("Jack Grealish",10,"F"),p("Erling Haaland",9,"F")],
  },
  {
    id: 1002,
    leagueId: 39,
    leagueSlug: "premier-league",
    season: 2025,
    round: "Matchday 28",
    date: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    venue: "Anfield",
    status: "1H",
    minute: 34,
    homeTeam: T.liverpool,
    awayTeam: T.chelsea,
    homeScore: 1,
    awayScore: 0,
    homeScoreHT: undefined,
    awayScoreHT: undefined,
    lineupHome: [p("Alisson Becker",1,"G"),p("Trent Alexander-Arnold",66,"D"),p("Ibrahima Konaté",5,"D"),p("Virgil van Dijk",4,"D"),p("Andrew Robertson",26,"D"),p("Alexis Mac Allister",10,"M"),p("Dominik Szoboszlai",8,"M"),p("Ryan Gravenberch",38,"M"),p("Mohamed Salah",11,"F"),p("Darwin Núñez",9,"F"),p("Luis Díaz",7,"F")],
    lineupAway: [p("Robert Sánchez",13,"G"),p("Reece James",24,"D"),p("Benoît Badiashile",4,"D"),p("Levi Colwill",26,"D"),p("Ben Chilwell",21,"D"),p("Enzo Fernández",8,"M"),p("Moisés Caicedo",25,"M"),p("Cole Palmer",20,"M"),p("Raheem Sterling",17,"F"),p("Nicolas Jackson",15,"F"),p("Noni Madueke",11,"F")],
  },
  {
    id: 1003,
    leagueId: 39,
    leagueSlug: "premier-league",
    season: 2025,
    round: "Matchday 27",
    date: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    venue: "Old Trafford",
    status: "FT",
    homeTeam: T.manUtd,
    awayTeam: T.tottenham,
    homeScore: 2,
    awayScore: 2,
    homeScoreHT: 1,
    awayScoreHT: 0,
    lineupHome: [p("André Onana",24,"G"),p("Diogo Dalot",20,"D"),p("Raphaël Varane",19,"D"),p("Harry Maguire",5,"D"),p("Luke Shaw",23,"D"),p("Sofyan Amrabat",4,"M"),p("Casemiro",18,"M"),p("Bruno Fernandes",8,"M"),p("Marcus Rashford",10,"F"),p("Rasmus Højlund",11,"F"),p("Alejandro Garnacho",49,"F")],
    lineupAway: [p("Guglielmo Vicario",1,"G"),p("Pedro Porro",23,"D"),p("Cristian Romero",17,"D"),p("Micky van de Ven",37,"D"),p("Destiny Udogie",38,"D"),p("Pape Matar Sarr",29,"M"),p("Rodrigo Bentancur",30,"M"),p("James Maddison",10,"M"),p("Brennan Johnson",22,"F"),p("Richarlison",9,"F"),p("Heung-min Son",7,"F")],
  },
  // --- La Liga ---
  {
    id: 2001,
    leagueId: 140,
    leagueSlug: "la-liga",
    season: 2025,
    round: "Matchday 28",
    date: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    venue: "Santiago Bernabéu",
    status: "NS",
    homeTeam: T.realMadrid,
    awayTeam: T.barcelona,
    lineupHome: [p("Thibaut Courtois",1,"G"),p("Dani Carvajal",2,"D"),p("Éder Militão",3,"D"),p("Antonio Rüdiger",22,"D"),p("Ferland Mendy",23,"D"),p("Aurélien Tchouaméni",18,"M"),p("Eduardo Camavinga",12,"M"),p("Jude Bellingham",5,"M"),p("Federico Valverde",15,"F"),p("Rodrygo",11,"F"),p("Vinícius Jr.",7,"F")],
    lineupAway: [p("Marc-André ter Stegen",1,"G"),p("Jules Koundé",23,"D"),p("Ronald Araújo",4,"D"),p("Andreas Christensen",15,"D"),p("Alejandro Balde",3,"D"),p("Pedri",8,"M"),p("Frenkie de Jong",21,"M"),p("Gavi",6,"M"),p("Lamine Yamal",27,"F"),p("Raphinha",11,"F"),p("Robert Lewandowski",9,"F")],
  },
  {
    id: 2002,
    leagueId: 140,
    leagueSlug: "la-liga",
    season: 2025,
    round: "Matchday 27",
    date: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    venue: "Civitas Metropolitano",
    status: "FT",
    homeTeam: T.atletico,
    awayTeam: T.sevilla,
    homeScore: 3,
    awayScore: 0,
    homeScoreHT: 1,
    awayScoreHT: 0,
    lineupHome: [p("Jan Oblak",13,"G"),p("Nahuel Molina",16,"D"),p("José María Giménez",2,"D"),p("Axel Witsel",20,"D"),p("Reinildo",6,"D"),p("Marcos Llorente",14,"M"),p("Rodrigo De Paul",5,"M"),p("Koke",6,"M"),p("Samuel Lino",8,"F"),p("Álvaro Morata",7,"F"),p("Antoine Griezmann",8,"F")],
    lineupAway: [p("Yassine Bounou",13,"G"),p("Gonzalo Montiel",2,"D"),p("Loïc Badé",5,"D"),p("Marcos Acuña",19,"D"),p("Jesús Navas",16,"D"),p("Joan Jordán",8,"M"),p("Fernando",6,"M"),p("Lucas Ocampos",5,"M"),p("Youssef En-Nesyri",15,"F"),p("Rafa Mir",21,"F"),p("Bryan Gil",17,"F")],
  },
  // --- Bundesliga ---
  {
    id: 3001,
    leagueId: 78,
    leagueSlug: "bundesliga",
    season: 2025,
    round: "Matchday 26",
    date: new Date(Date.now() - 3 * 86400 * 1000).toISOString(),
    venue: "Allianz Arena",
    status: "FT",
    homeTeam: T.bayernMunich,
    awayTeam: T.dortmund,
    homeScore: 3,
    awayScore: 1,
    homeScoreHT: 1,
    awayScoreHT: 1,
    lineupHome: [p("Manuel Neuer",1,"G"),p("Noussair Mazraoui",40,"D"),p("Kim Min-jae",3,"D"),p("Dayot Upamecano",2,"D"),p("Alphonso Davies",19,"D"),p("Joshua Kimmich",6,"M"),p("Leon Goretzka",8,"M"),p("Leroy Sané",10,"M"),p("Jamal Musiala",42,"F"),p("Kingsley Coman",11,"F"),p("Harry Kane",9,"F")],
    lineupAway: [p("Gregor Kobel",1,"G"),p("Julian Ryerson",24,"D"),p("Mats Hummels",15,"D"),p("Nico Schlotterbeck",4,"D"),p("Ian Maatsen",36,"D"),p("Emre Can",23,"M"),p("Marcel Sabitzer",14,"M"),p("Julien Duranville",16,"F"),p("Felix Nmecha",8,"F"),p("Karim Adeyemi",27,"F"),p("Sébastien Haller",9,"F")],
  },
  {
    id: 3002,
    leagueId: 78,
    leagueSlug: "bundesliga",
    season: 2025,
    round: "Matchday 27",
    date: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    venue: "BayArena",
    status: "2H",
    minute: 67,
    homeTeam: T.leverkusen,
    awayTeam: T.rbLeipzig,
    homeScore: 2,
    awayScore: 1,
    homeScoreHT: 1,
    awayScoreHT: 0,
  },
  // --- Serie A ---
  {
    id: 4001,
    leagueId: 135,
    leagueSlug: "serie-a",
    season: 2025,
    round: "Matchday 28",
    date: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
    venue: "San Siro",
    status: "NS",
    homeTeam: T.interMilan,
    awayTeam: T.juventus,
  },
  // --- Ligue 1 ---
  {
    id: 5001,
    leagueId: 61,
    leagueSlug: "ligue-1",
    season: 2025,
    round: "Matchday 27",
    date: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    venue: "Parc des Princes",
    status: "FT",
    homeTeam: T.psg,
    awayTeam: T.monaco,
    homeScore: 4,
    awayScore: 2,
    homeScoreHT: 2,
    awayScoreHT: 1,
  },
  // --- Champions League ---
  {
    id: 6001,
    leagueId: 2,
    leagueSlug: "champions-league",
    season: 2025,
    round: "Round of 16 - 2nd Leg",
    date: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    venue: "Santiago Bernabéu",
    status: "NS",
    homeTeam: T.realMadrid,
    awayTeam: T.manCity,
  },
  {
    id: 6002,
    leagueId: 2,
    leagueSlug: "champions-league",
    season: 2025,
    round: "Round of 16 - 2nd Leg",
    date: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    venue: "Estadio da Luz",
    status: "FT",
    homeTeam: T.benfica,
    awayTeam: T.arsenal,
    homeScore: 1,
    awayScore: 2,
    homeScoreHT: 0,
    awayScoreHT: 1,
  },
  // --- Eredivisie ---
  {
    id: 7001,
    leagueId: 88,
    leagueSlug: "eredivisie",
    season: 2025,
    round: "Matchday 27",
    date: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    venue: "Johan Cruyff Arena",
    status: "NS",
    homeTeam: T.ajax,
    awayTeam: T.psv,
  },
  {
    id: 7002,
    leagueId: 88,
    leagueSlug: "eredivisie",
    season: 2025,
    round: "Matchday 26",
    date: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    venue: "De Kuip",
    status: "FT",
    homeTeam: T.feyenoord,
    awayTeam: T.azAlkmaar,
    homeScore: 3,
    awayScore: 1,
    homeScoreHT: 1,
    awayScoreHT: 0,
  },
  // --- Primeira Liga ---
  {
    id: 8001,
    leagueId: 94,
    leagueSlug: "primeira-liga",
    season: 2025,
    round: "Matchday 27",
    date: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    venue: "Estádio do Dragão",
    status: "NS",
    homeTeam: T.porto,
    awayTeam: T.sporting,
  },
  {
    id: 8002,
    leagueId: 94,
    leagueSlug: "primeira-liga",
    season: 2025,
    round: "Matchday 26",
    date: new Date(Date.now() - 3 * 86400 * 1000).toISOString(),
    venue: "Estádio da Luz",
    status: "FT",
    homeTeam: T.portoBenfica,
    awayTeam: T.braga,
    homeScore: 2,
    awayScore: 0,
    homeScoreHT: 1,
    awayScoreHT: 0,
  },
  // --- Saudi Pro League ---
  {
    id: 9001,
    leagueId: 307,
    leagueSlug: "saudi-pro-league",
    season: 2025,
    round: "Matchday 25",
    date: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
    venue: "Al-Awwal Park",
    status: "NS",
    homeTeam: T.alNassr,
    awayTeam: T.alHilal,
  },
  {
    id: 9002,
    leagueId: 307,
    leagueSlug: "saudi-pro-league",
    season: 2025,
    round: "Matchday 24",
    date: new Date(Date.now() - 4 * 86400 * 1000).toISOString(),
    venue: "King Abdullah Sports City",
    status: "FT",
    homeTeam: T.alIttihad,
    awayTeam: T.alAhli,
    homeScore: 1,
    awayScore: 2,
    homeScoreHT: 0,
    awayScoreHT: 1,
  },
  // --- MLS ---
  {
    id: 10001,
    leagueId: 253,
    leagueSlug: "mls",
    season: 2025,
    round: "Week 10",
    date: new Date(Date.now() + 10 * 3600 * 1000).toISOString(),
    venue: "Chase Stadium",
    status: "NS",
    homeTeam: T.interMiami,
    awayTeam: T.laGalaxy,
  },
  {
    id: 10002,
    leagueId: 253,
    leagueSlug: "mls",
    season: 2025,
    round: "Week 9",
    date: new Date(Date.now() - 5 * 86400 * 1000).toISOString(),
    venue: "Lumen Field",
    status: "FT",
    homeTeam: T.seattle,
    awayTeam: T.portland,
    homeScore: 2,
    awayScore: 1,
    homeScoreHT: 1,
    awayScoreHT: 0,
  },
];

// ---------------------------------------------------------------------------
// MOCK_STANDINGS
// ---------------------------------------------------------------------------

export const MOCK_STANDINGS: Partial<Record<LeagueSlug, StandingEntry[]>> = {
  "premier-league": [
    {
      rank: 1,
      team: T.arsenal,
      points: 64,
      played: 28,
      won: 20,
      drawn: 4,
      lost: 4,
      goalsFor: 65,
      goalsAgainst: 28,
      goalDifference: 37,
      form: "WWWDW",
      description: "Champions League",
    },
    {
      rank: 2,
      team: T.manCity,
      points: 61,
      played: 28,
      won: 19,
      drawn: 4,
      lost: 5,
      goalsFor: 61,
      goalsAgainst: 33,
      goalDifference: 28,
      form: "WWLWW",
      description: "Champions League",
    },
    {
      rank: 3,
      team: T.liverpool,
      points: 59,
      played: 27,
      won: 18,
      drawn: 5,
      lost: 4,
      goalsFor: 72,
      goalsAgainst: 38,
      goalDifference: 34,
      form: "WDWWW",
      description: "Champions League",
    },
    {
      rank: 4,
      team: T.astonVilla,
      points: 53,
      played: 28,
      won: 16,
      drawn: 5,
      lost: 7,
      goalsFor: 58,
      goalsAgainst: 44,
      goalDifference: 14,
      form: "WDWLW",
      description: "Champions League",
    },
    {
      rank: 5,
      team: T.tottenham,
      points: 48,
      played: 28,
      won: 14,
      drawn: 6,
      lost: 8,
      goalsFor: 52,
      goalsAgainst: 46,
      goalDifference: 6,
      form: "WLWDW",
      description: "Europa League",
    },
    {
      rank: 6,
      team: T.chelsea,
      points: 45,
      played: 28,
      won: 13,
      drawn: 6,
      lost: 9,
      goalsFor: 50,
      goalsAgainst: 47,
      goalDifference: 3,
      form: "DWWLL",
      description: "Europa League",
    },
    {
      rank: 7,
      team: T.newcastle,
      points: 43,
      played: 28,
      won: 12,
      drawn: 7,
      lost: 9,
      goalsFor: 45,
      goalsAgainst: 40,
      goalDifference: 5,
      form: "DLWWD",
    },
    {
      rank: 8,
      team: T.manUtd,
      points: 35,
      played: 28,
      won: 9,
      drawn: 8,
      lost: 11,
      goalsFor: 30,
      goalsAgainst: 43,
      goalDifference: -13,
      form: "DLLDW",
    },
    { rank: 9,  team: T.brighton,      points: 33, played: 28, won: 9,  drawn: 6,  lost: 13, goalsFor: 42, goalsAgainst: 48, goalDifference: -6,  form: "WLLWL" },
    { rank: 10, team: T.wolves,        points: 30, played: 28, won: 8,  drawn: 6,  lost: 14, goalsFor: 36, goalsAgainst: 52, goalDifference: -16, form: "LWLLD" },
    { rank: 11, team: T.westHam,       points: 29, played: 28, won: 8,  drawn: 5,  lost: 15, goalsFor: 35, goalsAgainst: 54, goalDifference: -19, form: "LLDWL" },
    { rank: 12, team: T.fulham,        points: 28, played: 28, won: 7,  drawn: 7,  lost: 14, goalsFor: 34, goalsAgainst: 49, goalDifference: -15, form: "DLWLL" },
    { rank: 13, team: T.brentford,     points: 27, played: 28, won: 7,  drawn: 6,  lost: 15, goalsFor: 37, goalsAgainst: 52, goalDifference: -15, form: "LWLLD" },
    { rank: 14, team: T.crystalPalace, points: 26, played: 28, won: 7,  drawn: 5,  lost: 16, goalsFor: 30, goalsAgainst: 50, goalDifference: -20, form: "LLLWL" },
    { rank: 15, team: T.everton,       points: 25, played: 28, won: 6,  drawn: 7,  lost: 15, goalsFor: 28, goalsAgainst: 46, goalDifference: -18, form: "DLLWL" },
    { rank: 16, team: T.nottmForest,   points: 24, played: 28, won: 6,  drawn: 6,  lost: 16, goalsFor: 29, goalsAgainst: 52, goalDifference: -23, form: "LLDLL" },
    { rank: 17, team: T.bournemouth,   points: 23, played: 28, won: 5,  drawn: 8,  lost: 15, goalsFor: 30, goalsAgainst: 55, goalDifference: -25, form: "DLLDL", description: "Relegation" },
    { rank: 18, team: T.luton,         points: 18, played: 28, won: 3,  drawn: 9,  lost: 16, goalsFor: 25, goalsAgainst: 61, goalDifference: -36, form: "LLDLL", description: "Relegation" },
    { rank: 19, team: T.burnley,       points: 15, played: 28, won: 3,  drawn: 6,  lost: 19, goalsFor: 22, goalsAgainst: 65, goalDifference: -43, form: "LLLLL", description: "Relegation" },
    { rank: 20, team: T.sheffield,     points: 13, played: 28, won: 3,  drawn: 4,  lost: 21, goalsFor: 18, goalsAgainst: 68, goalDifference: -50, form: "LLLLL", description: "Relegation" },
  ],

  "la-liga": [
    {
      rank: 1,
      team: T.realMadrid,
      points: 66,
      played: 28,
      won: 21,
      drawn: 3,
      lost: 4,
      goalsFor: 68,
      goalsAgainst: 29,
      goalDifference: 39,
      form: "WWWWW",
      description: "Champions League",
    },
    {
      rank: 2,
      team: T.barcelona,
      points: 60,
      played: 28,
      won: 18,
      drawn: 6,
      lost: 4,
      goalsFor: 60,
      goalsAgainst: 34,
      goalDifference: 26,
      form: "DWWWW",
      description: "Champions League",
    },
    {
      rank: 3,
      team: T.atletico,
      points: 58,
      played: 28,
      won: 17,
      drawn: 7,
      lost: 4,
      goalsFor: 54,
      goalsAgainst: 27,
      goalDifference: 27,
      form: "WWDWW",
      description: "Champions League",
    },
    {
      rank: 4,
      team: T.realBetis,
      points: 44,
      played: 28,
      won: 13,
      drawn: 5,
      lost: 10,
      goalsFor: 42,
      goalsAgainst: 40,
      goalDifference: 2,
      form: "WLDWL",
      description: "Europa League",
    },
    {
      rank: 5,
      team: T.sevilla,
      points: 38,
      played: 28,
      won: 10,
      drawn: 8,
      lost: 10,
      goalsFor: 38,
      goalsAgainst: 42,
      goalDifference: -4,
      form: "LWDLW",
    },
    { rank: 6,  team: T.villarreal,     points: 36, played: 28, won: 10, drawn: 6,  lost: 12, goalsFor: 36, goalsAgainst: 40, goalDifference: -4,  form: "WLDDL" },
    { rank: 7,  team: T.realSociedad,   points: 35, played: 28, won: 9,  drawn: 8,  lost: 11, goalsFor: 34, goalsAgainst: 38, goalDifference: -4,  form: "DLWDL" },
    { rank: 8,  team: T.athleticBilbao, points: 34, played: 28, won: 9,  drawn: 7,  lost: 12, goalsFor: 32, goalsAgainst: 37, goalDifference: -5,  form: "WDLLD" },
    { rank: 9,  team: T.girona,         points: 32, played: 28, won: 8,  drawn: 8,  lost: 12, goalsFor: 35, goalsAgainst: 42, goalDifference: -7,  form: "LDDWL" },
    { rank: 10, team: T.osasuna,        points: 30, played: 28, won: 8,  drawn: 6,  lost: 14, goalsFor: 28, goalsAgainst: 42, goalDifference: -14, form: "LWLLD" },
    { rank: 11, team: T.getafe,         points: 28, played: 28, won: 7,  drawn: 7,  lost: 14, goalsFor: 26, goalsAgainst: 40, goalDifference: -14, form: "LLDWL" },
    { rank: 12, team: T.valencia,       points: 27, played: 28, won: 7,  drawn: 6,  lost: 15, goalsFor: 30, goalsAgainst: 46, goalDifference: -16, form: "LLDLW" },
    { rank: 13, team: T.celtaVigo,      points: 26, played: 28, won: 7,  drawn: 5,  lost: 16, goalsFor: 30, goalsAgainst: 48, goalDifference: -18, form: "LLLWL" },
    { rank: 14, team: T.rayo,           points: 25, played: 28, won: 6,  drawn: 7,  lost: 15, goalsFor: 28, goalsAgainst: 46, goalDifference: -18, form: "LDLWL" },
    { rank: 15, team: T.mallorca,       points: 24, played: 28, won: 6,  drawn: 6,  lost: 16, goalsFor: 24, goalsAgainst: 44, goalDifference: -20, form: "LLLLD" },
    { rank: 16, team: T.alaves,         points: 23, played: 28, won: 5,  drawn: 8,  lost: 15, goalsFor: 22, goalsAgainst: 42, goalDifference: -20, form: "DLDDL" },
    { rank: 17, team: T.lasPalmas,      points: 22, played: 28, won: 5,  drawn: 7,  lost: 16, goalsFor: 24, goalsAgainst: 48, goalDifference: -24, form: "DLLLD", description: "Relegation" },
    { rank: 18, team: T.cadiz,          points: 18, played: 28, won: 4,  drawn: 6,  lost: 18, goalsFor: 20, goalsAgainst: 54, goalDifference: -34, form: "LLLLL", description: "Relegation" },
    { rank: 19, team: T.almeria,        points: 14, played: 28, won: 3,  drawn: 5,  lost: 20, goalsFor: 18, goalsAgainst: 58, goalDifference: -40, form: "LLLLL", description: "Relegation" },
    { rank: 20, team: T.cadiz,          points: 12, played: 28, won: 2,  drawn: 6,  lost: 20, goalsFor: 16, goalsAgainst: 62, goalDifference: -46, form: "LLLLL", description: "Relegation" },
  ],

  "bundesliga": [
    {
      rank: 1,
      team: T.leverkusen,
      points: 68,
      played: 27,
      won: 22,
      drawn: 2,
      lost: 3,
      goalsFor: 72,
      goalsAgainst: 24,
      goalDifference: 48,
      form: "WWWWW",
      description: "Champions League",
    },
    {
      rank: 2,
      team: T.bayernMunich,
      points: 60,
      played: 27,
      won: 19,
      drawn: 3,
      lost: 5,
      goalsFor: 75,
      goalsAgainst: 36,
      goalDifference: 39,
      form: "WWWLW",
      description: "Champions League",
    },
    {
      rank: 3,
      team: T.rbLeipzig,
      points: 52,
      played: 27,
      won: 15,
      drawn: 7,
      lost: 5,
      goalsFor: 58,
      goalsAgainst: 38,
      goalDifference: 20,
      form: "DWWWD",
      description: "Champions League",
    },
    {
      rank: 4,
      team: T.dortmund,
      points: 48,
      played: 27,
      won: 14,
      drawn: 6,
      lost: 7,
      goalsFor: 52,
      goalsAgainst: 44,
      goalDifference: 8,
      form: "LWWDW",
      description: "Europa League",
    },
    {
      rank: 5,
      team: T.gladbach,
      points: 38,
      played: 27,
      won: 11,
      drawn: 5,
      lost: 11,
      goalsFor: 44,
      goalsAgainst: 50,
      goalDifference: -6,
      form: "WDLWL",
    },
    { rank: 6,  team: T.frankfurt,   points: 36, played: 27, won: 10, drawn: 6,  lost: 11, goalsFor: 44, goalsAgainst: 46, goalDifference: -2,  form: "WDDLW" },
    { rank: 7,  team: T.stuttgart,   points: 34, played: 27, won: 9,  drawn: 7,  lost: 11, goalsFor: 42, goalsAgainst: 46, goalDifference: -4,  form: "LWWDL" },
    { rank: 8,  team: T.freiburg,    points: 32, played: 27, won: 9,  drawn: 5,  lost: 13, goalsFor: 38, goalsAgainst: 44, goalDifference: -6,  form: "WLLDW" },
    { rank: 9,  team: T.wolfsburg,   points: 30, played: 27, won: 8,  drawn: 6,  lost: 13, goalsFor: 36, goalsAgainst: 46, goalDifference: -10, form: "LWDLL" },
    { rank: 10, team: T.augsburg,    points: 28, played: 27, won: 7,  drawn: 7,  lost: 13, goalsFor: 34, goalsAgainst: 44, goalDifference: -10, form: "LDWLD" },
    { rank: 11, team: T.unionBerlin, points: 26, played: 27, won: 7,  drawn: 5,  lost: 15, goalsFor: 30, goalsAgainst: 48, goalDifference: -18, form: "LLLWL" },
    { rank: 12, team: T.hoffenheim,  points: 24, played: 27, won: 6,  drawn: 6,  lost: 15, goalsFor: 30, goalsAgainst: 50, goalDifference: -20, form: "LLLDW" },
    { rank: 13, team: T.mainz,       points: 23, played: 27, won: 6,  drawn: 5,  lost: 16, goalsFor: 28, goalsAgainst: 52, goalDifference: -24, form: "LLLWL" },
    { rank: 14, team: T.werder,      points: 22, played: 27, won: 5,  drawn: 7,  lost: 15, goalsFor: 26, goalsAgainst: 52, goalDifference: -26, form: "DLLLL" },
    { rank: 15, team: T.heidenheim,  points: 20, played: 27, won: 5,  drawn: 5,  lost: 17, goalsFor: 28, goalsAgainst: 56, goalDifference: -28, form: "LLLLD", description: "Relegation" },
    { rank: 16, team: T.bochum,      points: 18, played: 27, won: 4,  drawn: 6,  lost: 17, goalsFor: 24, goalsAgainst: 58, goalDifference: -34, form: "LLLLL", description: "Relegation" },
    { rank: 17, team: T.cologne,     points: 15, played: 27, won: 3,  drawn: 6,  lost: 18, goalsFor: 20, goalsAgainst: 60, goalDifference: -40, form: "LLLLL", description: "Relegation" },
    { rank: 18, team: T.darmstadt,   points: 12, played: 27, won: 2,  drawn: 6,  lost: 19, goalsFor: 18, goalsAgainst: 66, goalDifference: -48, form: "LLLLL", description: "Relegation" },
  ],

  "serie-a": [
    {
      rank: 1,
      team: T.interMilan,
      points: 67,
      played: 28,
      won: 21,
      drawn: 4,
      lost: 3,
      goalsFor: 66,
      goalsAgainst: 22,
      goalDifference: 44,
      form: "WWWWW",
      description: "Champions League",
    },
    {
      rank: 2,
      team: T.juventus,
      points: 54,
      played: 28,
      won: 16,
      drawn: 6,
      lost: 6,
      goalsFor: 48,
      goalsAgainst: 28,
      goalDifference: 20,
      form: "WDWLW",
      description: "Champions League",
    },
    {
      rank: 3,
      team: T.acMilan,
      points: 51,
      played: 28,
      won: 15,
      drawn: 6,
      lost: 7,
      goalsFor: 50,
      goalsAgainst: 35,
      goalDifference: 15,
      form: "WWDLW",
      description: "Champions League",
    },
    {
      rank: 4,
      team: T.napoli,
      points: 47,
      played: 28,
      won: 14,
      drawn: 5,
      lost: 9,
      goalsFor: 52,
      goalsAgainst: 40,
      goalDifference: 12,
      form: "WLWWL",
      description: "Europa League",
    },
    {
      rank: 5,
      team: T.roma,
      points: 44,
      played: 28,
      won: 13,
      drawn: 5,
      lost: 10,
      goalsFor: 47,
      goalsAgainst: 42,
      goalDifference: 5,
      form: "LDWWW",
      description: "Europa League",
    },
    { rank: 6,  team: T.atalanta,   points: 42, played: 28, won: 12, drawn: 6,  lost: 10, goalsFor: 52, goalsAgainst: 40, goalDifference: 12,  form: "WWLDW" },
    { rank: 7,  team: T.lazio,      points: 40, played: 28, won: 12, drawn: 4,  lost: 12, goalsFor: 44, goalsAgainst: 42, goalDifference: 2,   form: "LWWLD" },
    { rank: 8,  team: T.fiorentina, points: 38, played: 28, won: 11, drawn: 5,  lost: 12, goalsFor: 40, goalsAgainst: 40, goalDifference: 0,   form: "DWWLL" },
    { rank: 9,  team: T.bologna,    points: 36, played: 28, won: 10, drawn: 6,  lost: 12, goalsFor: 38, goalsAgainst: 40, goalDifference: -2,  form: "LWDWL" },
    { rank: 10, team: T.torino,     points: 34, played: 28, won: 9,  drawn: 7,  lost: 12, goalsFor: 34, goalsAgainst: 40, goalDifference: -6,  form: "LWDLD" },
    { rank: 11, team: T.monza,      points: 30, played: 28, won: 8,  drawn: 6,  lost: 14, goalsFor: 30, goalsAgainst: 44, goalDifference: -14, form: "LWLLD" },
    { rank: 12, team: T.genoa,      points: 28, played: 28, won: 7,  drawn: 7,  lost: 14, goalsFor: 28, goalsAgainst: 46, goalDifference: -18, form: "DLLWL" },
    { rank: 13, team: T.udinese,    points: 26, played: 28, won: 6,  drawn: 8,  lost: 14, goalsFor: 26, goalsAgainst: 44, goalDifference: -18, form: "DLLLD" },
    { rank: 14, team: T.lecce,      points: 24, played: 28, won: 6,  drawn: 6,  lost: 16, goalsFor: 24, goalsAgainst: 50, goalDifference: -26, form: "LLLWL" },
    { rank: 15, team: T.empoli,     points: 22, played: 28, won: 5,  drawn: 7,  lost: 16, goalsFor: 22, goalsAgainst: 50, goalDifference: -28, form: "DLLLL" },
    { rank: 16, team: T.cagliari,   points: 20, played: 28, won: 5,  drawn: 5,  lost: 18, goalsFor: 24, goalsAgainst: 54, goalDifference: -30, form: "LLLLL" },
    { rank: 17, team: T.hellas,     points: 18, played: 28, won: 4,  drawn: 6,  lost: 18, goalsFor: 22, goalsAgainst: 56, goalDifference: -34, form: "LLLLL", description: "Relegation" },
    { rank: 18, team: T.frosinone,  points: 16, played: 28, won: 3,  drawn: 7,  lost: 18, goalsFor: 20, goalsAgainst: 58, goalDifference: -38, form: "LLLLL", description: "Relegation" },
    { rank: 19, team: T.salernitana,points: 12, played: 28, won: 2,  drawn: 6,  lost: 20, goalsFor: 18, goalsAgainst: 62, goalDifference: -44, form: "LLLLL", description: "Relegation" },
    { rank: 20, team: T.sassulo,    points: 10, played: 28, won: 2,  drawn: 4,  lost: 22, goalsFor: 16, goalsAgainst: 68, goalDifference: -52, form: "LLLLL", description: "Relegation" },
  ],

  "ligue-1": [
    {
      rank: 1,
      team: T.psg,
      points: 72,
      played: 27,
      won: 23,
      drawn: 3,
      lost: 1,
      goalsFor: 74,
      goalsAgainst: 25,
      goalDifference: 49,
      form: "WWWWW",
      description: "Champions League",
    },
    {
      rank: 2,
      team: T.monaco,
      points: 55,
      played: 27,
      won: 17,
      drawn: 4,
      lost: 6,
      goalsFor: 56,
      goalsAgainst: 36,
      goalDifference: 20,
      form: "WWLWW",
      description: "Champions League",
    },
    {
      rank: 3,
      team: T.marseille,
      points: 52,
      played: 27,
      won: 15,
      drawn: 7,
      lost: 5,
      goalsFor: 48,
      goalsAgainst: 32,
      goalDifference: 16,
      form: "WDWDW",
      description: "Champions League",
    },
    {
      rank: 4,
      team: T.lyon,
      points: 43,
      played: 27,
      won: 12,
      drawn: 7,
      lost: 8,
      goalsFor: 44,
      goalsAgainst: 40,
      goalDifference: 4,
      form: "DLWWL",
      description: "Europa League",
    },
    { rank: 5,  team: T.lille,       points: 40, played: 27, won: 12, drawn: 4,  lost: 11, goalsFor: 40, goalsAgainst: 38, goalDifference: 2,   form: "WLWDL" },
    { rank: 6,  team: T.nice,        points: 38, played: 27, won: 11, drawn: 5,  lost: 11, goalsFor: 38, goalsAgainst: 36, goalDifference: 2,   form: "LWWLD" },
    { rank: 7,  team: T.rennes,      points: 36, played: 27, won: 10, drawn: 6,  lost: 11, goalsFor: 36, goalsAgainst: 38, goalDifference: -2,  form: "WDLWL" },
    { rank: 8,  team: T.lens,        points: 34, played: 27, won: 9,  drawn: 7,  lost: 11, goalsFor: 34, goalsAgainst: 38, goalDifference: -4,  form: "DWWLL" },
    { rank: 9,  team: T.brest,       points: 32, played: 27, won: 9,  drawn: 5,  lost: 13, goalsFor: 32, goalsAgainst: 40, goalDifference: -8,  form: "LWWLL" },
    { rank: 10, team: T.toulouse,    points: 30, played: 27, won: 8,  drawn: 6,  lost: 13, goalsFor: 30, goalsAgainst: 42, goalDifference: -12, form: "LDLWL" },
    { rank: 11, team: T.reims,       points: 28, played: 27, won: 7,  drawn: 7,  lost: 13, goalsFor: 28, goalsAgainst: 40, goalDifference: -12, form: "DLLWD" },
    { rank: 12, team: T.strasbourg,  points: 26, played: 27, won: 7,  drawn: 5,  lost: 15, goalsFor: 26, goalsAgainst: 44, goalDifference: -18, form: "LLLWL" },
    { rank: 13, team: T.montpellier, points: 24, played: 27, won: 6,  drawn: 6,  lost: 15, goalsFor: 28, goalsAgainst: 48, goalDifference: -20, form: "LLDWL" },
    { rank: 14, team: T.nantes,      points: 22, played: 27, won: 5,  drawn: 7,  lost: 15, goalsFor: 24, goalsAgainst: 46, goalDifference: -22, form: "DLLLL" },
    { rank: 15, team: T.lorient,     points: 18, played: 27, won: 4,  drawn: 6,  lost: 17, goalsFor: 22, goalsAgainst: 54, goalDifference: -32, form: "LLLLL", description: "Relegation" },
    { rank: 16, team: T.leHavre,     points: 16, played: 27, won: 3,  drawn: 7,  lost: 17, goalsFor: 20, goalsAgainst: 56, goalDifference: -36, form: "LLLLL", description: "Relegation" },
    { rank: 17, team: T.metz,        points: 14, played: 27, won: 3,  drawn: 5,  lost: 19, goalsFor: 18, goalsAgainst: 60, goalDifference: -42, form: "LLLLL", description: "Relegation" },
    { rank: 18, team: T.clermont,    points: 10, played: 27, won: 2,  drawn: 4,  lost: 21, goalsFor: 14, goalsAgainst: 66, goalDifference: -52, form: "LLLLL", description: "Relegation" },
  ],

  "champions-league": [
    {
      rank: 1,
      team: T.realMadrid,
      points: 18,
      played: 8,
      won: 6,
      drawn: 0,
      lost: 2,
      goalsFor: 20,
      goalsAgainst: 8,
      goalDifference: 12,
      form: "WWWWW",
    },
    {
      rank: 2,
      team: T.manCity,
      points: 16,
      played: 8,
      won: 5,
      drawn: 1,
      lost: 2,
      goalsFor: 18,
      goalsAgainst: 10,
      goalDifference: 8,
      form: "WWDWW",
    },
    {
      rank: 3,
      team: T.arsenal,
      points: 15,
      played: 8,
      won: 5,
      drawn: 0,
      lost: 3,
      goalsFor: 15,
      goalsAgainst: 12,
      goalDifference: 3,
      form: "WWWLW",
    },
    {
      rank: 4,
      team: T.bayernMunich,
      points: 13,
      played: 8,
      won: 4,
      drawn: 1,
      lost: 3,
      goalsFor: 14,
      goalsAgainst: 11,
      goalDifference: 3,
      form: "WLWDW",
    },
    {
      rank: 5,
      team: T.psvEindhoven,
      points: 12,
      played: 8,
      won: 4,
      drawn: 0,
      lost: 4,
      goalsFor: 12,
      goalsAgainst: 14,
      goalDifference: -2,
      form: "WLWWL",
    },
  ],

  "eredivisie": [
    { rank: 1, team: T.psv,        points: 62, played: 26, won: 20, drawn: 2, lost: 4,  goalsFor: 68, goalsAgainst: 26, goalDifference: 42,  form: "WWWWW", description: "Champions League" },
    { rank: 2, team: T.ajax,       points: 54, played: 26, won: 17, drawn: 3, lost: 6,  goalsFor: 58, goalsAgainst: 30, goalDifference: 28,  form: "WWWDW", description: "Champions League" },
    { rank: 3, team: T.feyenoord,  points: 52, played: 26, won: 16, drawn: 4, lost: 6,  goalsFor: 54, goalsAgainst: 28, goalDifference: 26,  form: "WDWWW", description: "Champions League" },
    { rank: 4, team: T.azAlkmaar,  points: 46, played: 26, won: 14, drawn: 4, lost: 8,  goalsFor: 48, goalsAgainst: 34, goalDifference: 14,  form: "WWLDW", description: "Europa League" },
    { rank: 5, team: T.twente,     points: 42, played: 26, won: 13, drawn: 3, lost: 10, goalsFor: 42, goalsAgainst: 36, goalDifference: 6,   form: "WLWWL" },
    { rank: 6, team: T.utrechtTeam,points: 36, played: 26, won: 10, drawn: 6, lost: 10, goalsFor: 38, goalsAgainst: 40, goalDifference: -2,  form: "DWLWL" },
    { rank: 7, team: T.heerenveen, points: 28, played: 26, won: 8,  drawn: 4, lost: 14, goalsFor: 32, goalsAgainst: 48, goalDifference: -16, form: "LWLLD", description: "Relegation" },
    { rank: 8, team: T.groningen,  points: 18, played: 26, won: 4,  drawn: 6, lost: 16, goalsFor: 24, goalsAgainst: 58, goalDifference: -34, form: "LLLLL", description: "Relegation" },
  ],

  "primeira-liga": [
    { rank: 1, team: T.sporting,    points: 65, played: 26, won: 21, drawn: 2, lost: 3,  goalsFor: 60, goalsAgainst: 20, goalDifference: 40,  form: "WWWWW", description: "Champions League" },
    { rank: 2, team: T.portoBenfica,points: 58, played: 26, won: 18, drawn: 4, lost: 4,  goalsFor: 56, goalsAgainst: 24, goalDifference: 32,  form: "WWDWW", description: "Champions League" },
    { rank: 3, team: T.porto,       points: 55, played: 26, won: 17, drawn: 4, lost: 5,  goalsFor: 52, goalsAgainst: 26, goalDifference: 26,  form: "WDWWL", description: "Champions League" },
    { rank: 4, team: T.braga,       points: 44, played: 26, won: 13, drawn: 5, lost: 8,  goalsFor: 42, goalsAgainst: 30, goalDifference: 12,  form: "WLDWW", description: "Europa League" },
    { rank: 5, team: T.guimaraes,   points: 36, played: 26, won: 10, drawn: 6, lost: 10, goalsFor: 34, goalsAgainst: 36, goalDifference: -2,  form: "WDLWL" },
    { rank: 6, team: T.vitoria,     points: 30, played: 26, won: 8,  drawn: 6, lost: 12, goalsFor: 28, goalsAgainst: 38, goalDifference: -10, form: "LWWLL" },
    { rank: 7, team: T.farense,     points: 22, played: 26, won: 5,  drawn: 7, lost: 14, goalsFor: 22, goalsAgainst: 48, goalDifference: -26, form: "LLLLD", description: "Relegation" },
    { rank: 8, team: T.aves,        points: 16, played: 26, won: 3,  drawn: 7, lost: 16, goalsFor: 18, goalsAgainst: 56, goalDifference: -38, form: "LLLLL", description: "Relegation" },
  ],

  "saudi-pro-league": [
    { rank: 1, team: T.alHilal,   points: 60, played: 24, won: 19, drawn: 3, lost: 2,  goalsFor: 62, goalsAgainst: 22, goalDifference: 40,  form: "WWWWW" },
    { rank: 2, team: T.alNassr,   points: 52, played: 24, won: 16, drawn: 4, lost: 4,  goalsFor: 56, goalsAgainst: 26, goalDifference: 30,  form: "WWWDW" },
    { rank: 3, team: T.alIttihad, points: 48, played: 24, won: 14, drawn: 6, lost: 4,  goalsFor: 48, goalsAgainst: 28, goalDifference: 20,  form: "WWDWL" },
    { rank: 4, team: T.alAhli,    points: 42, played: 24, won: 12, drawn: 6, lost: 6,  goalsFor: 40, goalsAgainst: 30, goalDifference: 10,  form: "WDWWL" },
    { rank: 5, team: T.alQadsiah, points: 34, played: 24, won: 10, drawn: 4, lost: 10, goalsFor: 34, goalsAgainst: 38, goalDifference: -4,  form: "WLWDL" },
    { rank: 6, team: T.alFaisaly, points: 28, played: 24, won: 7,  drawn: 7, lost: 10, goalsFor: 28, goalsAgainst: 38, goalDifference: -10, form: "DLWLL" },
    { rank: 7, team: T.alShabbab, points: 22, played: 24, won: 5,  drawn: 7, lost: 12, goalsFor: 24, goalsAgainst: 44, goalDifference: -20, form: "LLDWL" },
    { rank: 8, team: T.alTaawoun, points: 16, played: 24, won: 3,  drawn: 7, lost: 14, goalsFor: 20, goalsAgainst: 52, goalDifference: -32, form: "LLLLL" },
  ],

  "mls": [
    { rank: 1, team: T.interMiami, points: 48, played: 20, won: 14, drawn: 6, lost: 0,  goalsFor: 48, goalsAgainst: 18, goalDifference: 30,  form: "WWWWW" },
    { rank: 2, team: T.laGalaxy,   points: 38, played: 20, won: 11, drawn: 5, lost: 4,  goalsFor: 38, goalsAgainst: 24, goalDifference: 14,  form: "WWDWL" },
    { rank: 3, team: T.seattle,    points: 34, played: 20, won: 10, drawn: 4, lost: 6,  goalsFor: 34, goalsAgainst: 26, goalDifference: 8,   form: "WLWWL" },
    { rank: 4, team: T.portland,   points: 30, played: 20, won: 8,  drawn: 6, lost: 6,  goalsFor: 30, goalsAgainst: 28, goalDifference: 2,   form: "DWWLL" },
    { rank: 5, team: T.atlAtlanta, points: 26, played: 20, won: 7,  drawn: 5, lost: 8,  goalsFor: 26, goalsAgainst: 30, goalDifference: -4,  form: "WLLDW" },
    { rank: 6, team: T.nycfc,      points: 22, played: 20, won: 6,  drawn: 4, lost: 10, goalsFor: 24, goalsAgainst: 34, goalDifference: -10, form: "LLWDL" },
    { rank: 7, team: T.chicagoFire,points: 18, played: 20, won: 4,  drawn: 6, lost: 10, goalsFor: 20, goalsAgainst: 36, goalDifference: -16, form: "LLDLL" },
    { rank: 8, team: T.nycRB,      points: 14, played: 20, won: 3,  drawn: 5, lost: 12, goalsFor: 18, goalsAgainst: 42, goalDifference: -24, form: "LLLLL" },
  ],
};

// ---------------------------------------------------------------------------
// MOCK_SQUADS – representative squads per team (for Player Modal)
// ---------------------------------------------------------------------------

export interface MockPlayer {
  id: number;
  name: string;
  nameKo?: string;
  position: "GK" | "DEF" | "MID" | "FWD";
  number: number;
  nationality: string;
  height?: string;
  weight?: string;
  age?: number;
  goals?: number;
  assists?: number;
  appearances?: number;
  marketValue?: string;
}

export const MOCK_SQUADS: Record<string, MockPlayer[]> = {
  // ── Arsenal (2025/26) ────────────────────────────────────────────────────────
  "arsenal": [
    { id: 2931,  name: "David Raya",    position: "GK",  number: 22, nationality: "Spain",   height: "183cm", weight: "79kg", age: 30, goals: 0,  assists: 0,  appearances: 27, marketValue: "€28M" },
    { id: 276460,name: "Ben White",     position: "DEF", number: 4,  nationality: "England", height: "186cm", weight: "75kg", age: 27, goals: 1,  assists: 4,  appearances: 21, marketValue: "€42M" },
    { id: 346524,name: "William Saliba",position: "DEF", number: 12, nationality: "France",  height: "192cm", weight: "82kg", age: 24, goals: 2,  assists: 2,  appearances: 27, marketValue: "€95M" },
    { id: 22698, name: "Gabriel",       position: "DEF", number: 6,  nationality: "Brazil",  height: "190cm", weight: "78kg", age: 27, goals: 3,  assists: 1,  appearances: 24, marketValue: "€55M" },
    { id: 7178,  name: "Oleksandr Zinchenko", position: "DEF", number: 35, nationality: "Ukraine", height: "175cm", weight: "64kg", age: 28, goals: 0, assists: 3, appearances: 17, marketValue: "€25M" },
    { id: 748,   name: "Thomas Partey", position: "MID", number: 5,  nationality: "Ghana",   height: "185cm", weight: "77kg", age: 31, goals: 1,  assists: 2,  appearances: 14, marketValue: "€15M" },
    { id: 19916, name: "Martin Ødegaard",position: "MID",number: 8, nationality: "Norway",  height: "178cm", weight: "68kg", age: 26, goals: 11, assists: 10, appearances: 26, marketValue: "€120M" },
    { id: 1668,  name: "Declan Rice",   position: "MID", number: 41, nationality: "England", height: "185cm", weight: "79kg", age: 26, goals: 8,  assists: 7,  appearances: 27, marketValue: "€135M" },
    { id: 4710,  name: "Bukayo Saka",   position: "FWD", number: 7,  nationality: "England", height: "178cm", weight: "76kg", age: 23, goals: 16, assists: 13, appearances: 27, marketValue: "€180M" },
    { id: 285992,name: "Leandro Trossard", position: "FWD", number: 19, nationality: "Belgium", height: "173cm", weight: "67kg", age: 30, goals: 7, assists: 4, appearances: 22, marketValue: "€32M" },
    { id: 198978,name: "Kai Havertz",   position: "FWD", number: 29, nationality: "Germany", height: "189cm", weight: "79kg", age: 26, goals: 14, assists: 5,  appearances: 25, marketValue: "€72M" },
  ],
  // ── Real Madrid (2025/26) — Mbappé 합류, Kroos 은퇴 반영 ──────────────────────
  "real-madrid": [
    { id: 633,   name: "Thibaut Courtois", position: "GK", number: 1, nationality: "Belgium", height: "199cm", weight: "96kg", age: 33, goals: 0, assists: 0, appearances: 22, marketValue: "€30M" },
    { id: 635,   name: "Dani Carvajal", position: "DEF", number: 2, nationality: "Spain", height: "173cm", weight: "73kg", age: 33, goals: 1, assists: 2, appearances: 20, marketValue: "€15M" },
    { id: 154297,name: "Eder Militão",  position: "DEF", number: 3, nationality: "Brazil", height: "186cm", weight: "79kg", age: 27, goals: 1, assists: 0, appearances: 21, marketValue: "€65M" },
    { id: 198998,name: "Antonio Rüdiger", position: "DEF", number: 22, nationality: "Germany", height: "190cm", weight: "85kg", age: 32, goals: 2, assists: 1, appearances: 25, marketValue: "€28M" },
    { id: 162,   name: "Ferland Mendy", position: "DEF", number: 23, nationality: "France", height: "180cm", weight: "76kg", age: 30, goals: 0, assists: 2, appearances: 19, marketValue: "€30M" },
    { id: 342966,name: "Aurélien Tchouaméni", position: "MID", number: 18, nationality: "France", height: "187cm", weight: "78kg", age: 25, goals: 3, assists: 2, appearances: 24, marketValue: "€85M" },
    { id: 184,   name: "Luka Modrić",   position: "MID", number: 10, nationality: "Croatia", height: "172cm", weight: "66kg", age: 40, goals: 2, assists: 4, appearances: 20, marketValue: "€5M" },
    { id: 148361,name: "Jude Bellingham", position: "MID", number: 5, nationality: "England", height: "186cm", weight: "75kg", age: 21, goals: 20, assists: 9, appearances: 26, marketValue: "€220M" },
    { id: 47370, name: "Vinícius Jr.",  position: "FWD", number: 7,  nationality: "Brazil", height: "176cm", weight: "73kg", age: 24, goals: 21, assists: 9, appearances: 25, marketValue: "€200M" },
    { id: 278122,name: "Kylian Mbappé", position: "FWD", number: 9,  nationality: "France", height: "178cm", weight: "73kg", age: 26, goals: 28, assists: 8, appearances: 27, marketValue: "€200M" },
    { id: 289997,name: "Rodrygo",       position: "FWD", number: 11, nationality: "Brazil", height: "174cm", weight: "68kg", age: 24, goals: 10, assists: 6, appearances: 24, marketValue: "€85M" },
  ],
  // ── Liverpool (2025/26) ───────────────────────────────────────────────────────
  "liverpool": [
    { id: 1467,  name: "Alisson Becker", position: "GK", number: 1, nationality: "Brazil", height: "193cm", weight: "91kg", age: 32, goals: 0, assists: 0, appearances: 24, marketValue: "€30M" },
    { id: 19197, name: "Trent Alexander-Arnold", position: "DEF", number: 66, nationality: "England", height: "180cm", weight: "69kg", age: 26, goals: 4, assists: 10, appearances: 26, marketValue: "€90M" },
    { id: 1084,  name: "Virgil van Dijk", position: "DEF", number: 4, nationality: "Netherlands", height: "193cm", weight: "92kg", age: 33, goals: 4, assists: 2, appearances: 26, marketValue: "€40M" },
    { id: 288791,name: "Ibrahima Konaté", position: "DEF", number: 5, nationality: "France", height: "194cm", weight: "91kg", age: 26, goals: 2, assists: 0, appearances: 21, marketValue: "€70M" },
    { id: 19220, name: "Andrew Robertson", position: "DEF", number: 26, nationality: "Scotland", height: "178cm", weight: "64kg", age: 31, goals: 1, assists: 5, appearances: 23, marketValue: "€28M" },
    { id: 303958,name: "Alexis Mac Allister", position: "MID", number: 10, nationality: "Argentina", height: "174cm", weight: "72kg", age: 26, goals: 7, assists: 6, appearances: 26, marketValue: "€75M" },
    { id: 317453,name: "Dominik Szoboszlai", position: "MID", number: 8, nationality: "Hungary", height: "186cm", weight: "74kg", age: 24, goals: 6, assists: 9, appearances: 25, marketValue: "€75M" },
    { id: 306,   name: "Mohamed Salah", position: "FWD", number: 11, nationality: "Egypt", height: "175cm", weight: "71kg", age: 33, goals: 24, assists: 13, appearances: 27, marketValue: "€55M" },
    { id: 289478,name: "Luis Díaz",     position: "FWD", number: 7,  nationality: "Colombia", height: "180cm", weight: "73kg", age: 28, goals: 13, assists: 6, appearances: 23, marketValue: "€105M" },
    { id: 161693,name: "Darwin Núñez",  position: "FWD", number: 9,  nationality: "Uruguay", height: "187cm", weight: "81kg", age: 25, goals: 15, assists: 7, appearances: 25, marketValue: "€90M" },
    { id: 318217,name: "Cody Gakpo",    position: "FWD", number: 18, nationality: "Netherlands", height: "189cm", weight: "80kg", age: 26, goals: 9, assists: 5, appearances: 24, marketValue: "€68M" },
  ],
  // ── FC Barcelona (2025/26) ────────────────────────────────────────────────────
  "barcelona": [
    { id: 40,    name: "Marc-André ter Stegen", position: "GK", number: 1, nationality: "Germany", height: "187cm", weight: "85kg", age: 33, goals: 0, assists: 0, appearances: 25, marketValue: "€18M" },
    { id: 345854,name: "Jules Koundé", position: "DEF", number: 23, nationality: "France", height: "181cm", weight: "70kg", age: 26, goals: 3, assists: 3, appearances: 25, marketValue: "€75M" },
    { id: 155772,name: "Ronald Araújo", position: "DEF", number: 4, nationality: "Uruguay", height: "188cm", weight: "84kg", age: 26, goals: 1, assists: 0, appearances: 19, marketValue: "€80M" },
    { id: 67372, name: "Andreas Christensen", position: "DEF", number: 15, nationality: "Denmark", height: "185cm", weight: "76kg", age: 29, goals: 0, assists: 1, appearances: 17, marketValue: "€25M" },
    { id: 1028714,name: "Alejandro Balde", position: "DEF", number: 3, nationality: "Spain", height: "180cm", weight: "70kg", age: 21, goals: 2, assists: 6, appearances: 24, marketValue: "€65M" },
    { id: 290420,name: "Frenkie de Jong", position: "MID", number: 21, nationality: "Netherlands", height: "180cm", weight: "72kg", age: 27, goals: 3, assists: 5, appearances: 20, marketValue: "€55M" },
    { id: 310978,name: "Pedri",         position: "MID", number: 8, nationality: "Spain", height: "174cm", weight: "60kg", age: 22, goals: 7, assists: 8, appearances: 22, marketValue: "€150M" },
    { id: 311013,name: "Gavi",          position: "MID", number: 6, nationality: "Spain", height: "173cm", weight: "60kg", age: 20, goals: 4, assists: 6, appearances: 20, marketValue: "€110M" },
    { id: 191,   name: "Robert Lewandowski", position: "FWD", number: 9, nationality: "Poland", height: "184cm", weight: "80kg", age: 37, goals: 14, assists: 4, appearances: 24, marketValue: "€12M" },
    { id: 1225791,name: "Lamine Yamal", position: "FWD", number: 27, nationality: "Spain", height: "177cm", weight: "68kg", age: 17, goals: 12, assists: 12, appearances: 26, marketValue: "€250M" },
    { id: 302769,name: "Raphinha",      position: "FWD", number: 11, nationality: "Brazil", height: "176cm", weight: "64kg", age: 28, goals: 14, assists: 9, appearances: 26, marketValue: "€90M" },
  ],
  // ── Manchester City (2025/26) ─────────────────────────────────────────────────
  "man-city": [
    { id: 121723,name: "Ederson",       position: "GK",  number: 31, nationality: "Brazil",  height: "188cm", weight: "86kg", age: 31, goals: 0, assists: 0, appearances: 25, marketValue: "€35M" },
    { id: 627,   name: "Kyle Walker",   position: "DEF", number: 2,  nationality: "England", height: "178cm", weight: "70kg", age: 35, goals: 0, assists: 1, appearances: 20, marketValue: "€8M" },
    { id: 152476,name: "Rúben Dias",    position: "DEF", number: 3,  nationality: "Portugal",height: "187cm", weight: "76kg", age: 28, goals: 2, assists: 1, appearances: 25, marketValue: "€80M" },
    { id: 343060,name: "Manuel Akanji", position: "DEF", number: 25, nationality: "Switzerland", height: "187cm", weight: "80kg", age: 30, goals: 1, assists: 0, appearances: 24, marketValue: "€48M" },
    { id: 48971, name: "Kevin De Bruyne", position: "MID", number: 17, nationality: "Belgium", height: "181cm", weight: "68kg", age: 34, goals: 4, assists: 11, appearances: 20, marketValue: "€30M" },
    { id: 106889,name: "Rodri",         position: "MID", number: 16, nationality: "Spain",   height: "191cm", weight: "82kg", age: 28, goals: 3, assists: 5, appearances: 22, marketValue: "€130M" },
    { id: 193543,name: "Phil Foden",    position: "MID", number: 47, nationality: "England", height: "171cm", weight: "69kg", age: 25, goals: 16, assists: 8, appearances: 26, marketValue: "€160M" },
    { id: 67254, name: "Bernardo Silva",position: "MID", number: 20, nationality: "Portugal",height: "173cm", weight: "64kg", age: 30, goals: 6, assists: 7, appearances: 25, marketValue: "€75M" },
    { id: 1100,  name: "Erling Haaland",position: "FWD", number: 9,  nationality: "Norway",  height: "194cm", weight: "88kg", age: 25, goals: 27, assists: 6, appearances: 25, marketValue: "€220M" },
    { id: 389078,name: "Jeremy Doku",   position: "FWD", number: 11, nationality: "Belgium", height: "170cm", weight: "58kg", age: 23, goals: 7, assists: 10, appearances: 24, marketValue: "€85M" },
    { id: 184087,name: "Jack Grealish", position: "FWD", number: 10, nationality: "England", height: "180cm", weight: "68kg", age: 30, goals: 4, assists: 5, appearances: 16, marketValue: "€40M" },
  ],
  // ── Bayern Munich (2025/26) — Florian Wirtz 합류 ─────────────────────────────
  "bayern-munich": [
    { id: 183,   name: "Manuel Neuer",  position: "GK",  number: 1, nationality: "Germany", height: "193cm", weight: "92kg", age: 39, goals: 0, assists: 0, appearances: 18, marketValue: "€4M" },
    { id: 200890,name: "Dayot Upamecano", position: "DEF", number: 2, nationality: "France", height: "186cm", weight: "80kg", age: 26, goals: 1, assists: 1, appearances: 22, marketValue: "€58M" },
    { id: 280038,name: "Kim Min-jae",   position: "DEF", number: 3,  nationality: "South Korea", height: "190cm", weight: "87kg", age: 28, goals: 2, assists: 0, appearances: 21, marketValue: "€52M" },
    { id: 199009,name: "Alphonso Davies", position: "DEF", number: 19, nationality: "Canada", height: "183cm", weight: "76kg", age: 24, goals: 1, assists: 6, appearances: 23, marketValue: "€65M" },
    { id: 197017,name: "Joshua Kimmich", position: "MID", number: 6, nationality: "Germany", height: "177cm", weight: "73kg", age: 30, goals: 3, assists: 11, appearances: 25, marketValue: "€60M" },
    { id: 320001,name: "Jamal Musiala", position: "MID", number: 42, nationality: "Germany", height: "179cm", weight: "72kg", age: 22, goals: 15, assists: 11, appearances: 26, marketValue: "€180M" },
    { id: 199011,name: "Leon Goretzka", position: "MID", number: 8,  nationality: "Germany", height: "189cm", weight: "82kg", age: 30, goals: 3, assists: 4, appearances: 19, marketValue: "€35M" },
    { id: 324494,name: "Konrad Laimer", position: "MID", number: 27, nationality: "Austria", height: "181cm", weight: "76kg", age: 28, goals: 3, assists: 4, appearances: 21, marketValue: "€38M" },
    { id: 506215,name: "Florian Wirtz", position: "MID", number: 10, nationality: "Germany", height: "176cm", weight: "66kg", age: 22, goals: 12, assists: 14, appearances: 26, marketValue: "€150M" },
    { id: 184942,name: "Harry Kane",    position: "FWD", number: 9,  nationality: "England", height: "188cm", weight: "86kg", age: 32, goals: 28, assists: 10, appearances: 27, marketValue: "€80M" },
    { id: 19247, name: "Leroy Sané",    position: "FWD", number: 11, nationality: "Germany", height: "183cm", weight: "75kg", age: 29, goals: 10, assists: 11, appearances: 24, marketValue: "€45M" },
  ],
  // ── Paris Saint-Germain (2025/26) — 음바페 이적 후 스쿼드 ──────────────────────
  "paris-sg": [
    { id: 2039,  name: "Gianluigi Donnarumma", position: "GK", number: 99, nationality: "Italy", height: "196cm", weight: "90kg", age: 26, goals: 0, assists: 0, appearances: 24, marketValue: "€65M" },
    { id: 150890,name: "Achraf Hakimi", position: "DEF", number: 2, nationality: "Morocco", height: "181cm", weight: "73kg", age: 26, goals: 4, assists: 9, appearances: 25, marketValue: "€75M" },
    { id: 722,   name: "Marquinhos",    position: "DEF", number: 5, nationality: "Brazil", height: "183cm", weight: "75kg", age: 31, goals: 2, assists: 1, appearances: 23, marketValue: "€28M" },
    { id: 412198,name: "Lucas Beraldo", position: "DEF", number: 35, nationality: "Brazil", height: "187cm", weight: "80kg", age: 21, goals: 1, assists: 0, appearances: 19, marketValue: "€35M" },
    { id: 323507,name: "Nuno Mendes",   position: "DEF", number: 25, nationality: "Portugal", height: "180cm", weight: "70kg", age: 23, goals: 1, assists: 5, appearances: 21, marketValue: "€75M" },
    { id: 326789,name: "Vitinha",       position: "MID", number: 17, nationality: "Portugal", height: "169cm", weight: "62kg", age: 25, goals: 5, assists: 7, appearances: 26, marketValue: "€85M" },
    { id: 1159468,name: "Warren Zaïre-Emery", position: "MID", number: 33, nationality: "France", height: "180cm", weight: "70kg", age: 19, goals: 5, assists: 6, appearances: 24, marketValue: "€90M" },
    { id: 2117,  name: "Fabian Ruiz",   position: "MID", number: 8, nationality: "Spain", height: "189cm", weight: "79kg", age: 28, goals: 5, assists: 7, appearances: 23, marketValue: "€52M" },
    { id: 366703,name: "João Neves",    position: "MID", number: 87, nationality: "Portugal", height: "173cm", weight: "64kg", age: 20, goals: 3, assists: 5, appearances: 24, marketValue: "€100M" },
    { id: 37225, name: "Ousmane Dembélé", position: "FWD", number: 10, nationality: "France", height: "178cm", weight: "67kg", age: 27, goals: 13, assists: 15, appearances: 26, marketValue: "€100M" },
    { id: 285978,name: "Gonçalo Ramos", position: "FWD", number: 9, nationality: "Portugal", height: "187cm", weight: "82kg", age: 24, goals: 12, assists: 5, appearances: 22, marketValue: "€70M" },
  ],
  // ── Inter Milan (2025/26) ─────────────────────────────────────────────────────
  "inter-milan": [
    { id: 18945, name: "Yann Sommer",   position: "GK",  number: 1, nationality: "Switzerland", height: "183cm", weight: "80kg", age: 36, goals: 0, assists: 0, appearances: 26, marketValue: "€6M" },
    { id: 150916,name: "Denzel Dumfries", position: "DEF", number: 2, nationality: "Netherlands", height: "187cm", weight: "83kg", age: 29, goals: 3, assists: 6, appearances: 23, marketValue: "€38M" },
    { id: 5764,  name: "Francesco Acerbi", position: "DEF", number: 15, nationality: "Italy", height: "192cm", weight: "84kg", age: 37, goals: 1, assists: 0, appearances: 22, marketValue: "€4M" },
    { id: 326453,name: "Alessandro Bastoni", position: "DEF", number: 95, nationality: "Italy", height: "191cm", weight: "84kg", age: 25, goals: 2, assists: 4, appearances: 25, marketValue: "€95M" },
    { id: 2307,  name: "Federico Dimarco", position: "DEF", number: 32, nationality: "Italy", height: "175cm", weight: "70kg", age: 27, goals: 4, assists: 8, appearances: 24, marketValue: "€68M" },
    { id: 316319,name: "Nicolò Barella", position: "MID", number: 23, nationality: "Italy", height: "172cm", weight: "68kg", age: 28, goals: 6, assists: 9, appearances: 26, marketValue: "€85M" },
    { id: 25842, name: "Hakan Çalhanoğlu", position: "MID", number: 20, nationality: "Turkey", height: "179cm", weight: "69kg", age: 31, goals: 9, assists: 10, appearances: 25, marketValue: "€42M" },
    { id: 614,   name: "Henrikh Mkhitaryan", position: "MID", number: 22, nationality: "Armenia", height: "177cm", weight: "73kg", age: 37, goals: 3, assists: 4, appearances: 19, marketValue: "€4M" },
    { id: 127419,name: "Lautaro Martínez", position: "FWD", number: 10, nationality: "Argentina", height: "174cm", weight: "72kg", age: 27, goals: 24, assists: 7, appearances: 26, marketValue: "€120M" },
    { id: 47022, name: "Marcus Thuram", position: "FWD", number: 9, nationality: "France", height: "192cm", weight: "84kg", age: 27, goals: 16, assists: 8, appearances: 25, marketValue: "€88M" },
    { id: 4217,  name: "Marko Arnautović", position: "FWD", number: 8, nationality: "Austria", height: "192cm", weight: "86kg", age: 36, goals: 3, assists: 1, appearances: 14, marketValue: "€3M" },
  ],
};
