const FLAGS: Record<string, string> = {
  "Albania": "🇦🇱",
  "Algeria": "🇩🇿",
  "Argentina": "🇦🇷",
  "Australia": "🇦🇺",
  "Austria": "🇦🇹",
  "Belgium": "🇧🇪",
  "Bolivia": "🇧🇴",
  "Bosnia": "🇧🇦",
  "Brazil": "🇧🇷",
  "Cameroon": "🇨🇲",
  "Canada": "🇨🇦",
  "Chile": "🇨🇱",
  "China": "🇨🇳",
  "Colombia": "🇨🇴",
  "Congo": "🇨🇩",
  "Costa Rica": "🇨🇷",
  "Croatia": "🇭🇷",
  "Czech Republic": "🇨🇿",
  "Denmark": "🇩🇰",
  "Ecuador": "🇪🇨",
  "Egypt": "🇪🇬",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Finland": "🇫🇮",
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Ghana": "🇬🇭",
  "Greece": "🇬🇷",
  "Guinea": "🇬🇳",
  "Honduras": "🇭🇳",
  "Hungary": "🇭🇺",
  "Ireland": "🇮🇪",
  "Italy": "🇮🇹",
  "Ivory Coast": "🇨🇮",
  "Jamaica": "🇯🇲",
  "Japan": "🇯🇵",
  "Kosovo": "🇽🇰",
  "Mali": "🇲🇱",
  "Mexico": "🇲🇽",
  "Morocco": "🇲🇦",
  "Mozambique": "🇲🇿",
  "Netherlands": "🇳🇱",
  "Nigeria": "🇳🇬",
  "Norway": "🇳🇴",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Romania": "🇷🇴",
  "Russia": "🇷🇺",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Senegal": "🇸🇳",
  "Serbia": "🇷🇸",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  "Spain": "🇪🇸",
  "Sweden": "🇸🇪",
  "Switzerland": "🇨🇭",
  "Turkey": "🇹🇷",
  "Ukraine": "🇺🇦",
  "United States": "🇺🇸",
  "Uruguay": "🇺🇾",
  "Venezuela": "🇻🇪",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
};

export function nationalityFlag(nationality: string): string {
  return FLAGS[nationality] ?? "🌍";
}
