import type { LeagueSlug } from "./types";

export interface TeamEntry {
  slug:       string;    // canonical URL slug — same as the registry key
  id:         number;    // API-Football team ID
  leagueSlug: LeagueSlug;
  nameEn:     string;
  nameKo:     string;
  flag:       string;
}

// ─── Registry ──────────────────────────────────────────────────────────────────
// Each entry carries its own `slug` field so consumers never need a reverse-
// lookup. The Record key and `entry.slug` are always the same string.

export const TEAM_REGISTRY: Record<string, TeamEntry> = {
  // ── Premier League (20팀) ────────────────────────────────────────────────────
  "arsenal":           { slug: "arsenal",           id: 42,   leagueSlug: "premier-league", nameEn: "Arsenal",            nameKo: "아스널",               flag: "🔴" },
  "man-city":          { slug: "man-city",           id: 50,   leagueSlug: "premier-league", nameEn: "Man City",           nameKo: "맨체스터 시티",         flag: "🔵" },
  "liverpool":         { slug: "liverpool",          id: 40,   leagueSlug: "premier-league", nameEn: "Liverpool",          nameKo: "리버풀",               flag: "🔴" },
  "chelsea":           { slug: "chelsea",            id: 49,   leagueSlug: "premier-league", nameEn: "Chelsea",            nameKo: "첼시",                 flag: "🔵" },
  "man-united":        { slug: "man-united",         id: 33,   leagueSlug: "premier-league", nameEn: "Man United",         nameKo: "맨체스터 유나이티드",   flag: "🔴" },
  "tottenham":         { slug: "tottenham",          id: 47,   leagueSlug: "premier-league", nameEn: "Tottenham",          nameKo: "토트넘",               flag: "⚪" },
  "newcastle":         { slug: "newcastle",          id: 34,   leagueSlug: "premier-league", nameEn: "Newcastle",          nameKo: "뉴캐슬",               flag: "⚫" },
  "aston-villa":       { slug: "aston-villa",        id: 66,   leagueSlug: "premier-league", nameEn: "Aston Villa",        nameKo: "아스턴 빌라",           flag: "🟣" },
  "brighton":          { slug: "brighton",           id: 51,   leagueSlug: "premier-league", nameEn: "Brighton",           nameKo: "브라이턴",             flag: "🔵" },
  "brentford":         { slug: "brentford",          id: 55,   leagueSlug: "premier-league", nameEn: "Brentford",          nameKo: "브렌트퍼드",            flag: "🔴" },
  "fulham":            { slug: "fulham",             id: 36,   leagueSlug: "premier-league", nameEn: "Fulham",             nameKo: "풀럼",                 flag: "⚪" },
  "wolves":            { slug: "wolves",             id: 39,   leagueSlug: "premier-league", nameEn: "Wolves",             nameKo: "울버햄튼",             flag: "🟡" },
  "west-ham":          { slug: "west-ham",           id: 48,   leagueSlug: "premier-league", nameEn: "West Ham",           nameKo: "웨스트햄",             flag: "🔵" },
  "crystal-palace":    { slug: "crystal-palace",     id: 52,   leagueSlug: "premier-league", nameEn: "Crystal Palace",     nameKo: "크리스털 팰리스",       flag: "🔵" },
  "everton":           { slug: "everton",            id: 45,   leagueSlug: "premier-league", nameEn: "Everton",            nameKo: "에버턴",               flag: "🔵" },
  "nottm-forest":      { slug: "nottm-forest",       id: 65,   leagueSlug: "premier-league", nameEn: "Nottm Forest",       nameKo: "노팅엄 포레스트",       flag: "🔴" },
  "bournemouth":       { slug: "bournemouth",        id: 35,   leagueSlug: "premier-league", nameEn: "Bournemouth",        nameKo: "본머스",               flag: "🔴" },
  "ipswich":           { slug: "ipswich",            id: 57,   leagueSlug: "premier-league", nameEn: "Ipswich",            nameKo: "입스위치",             flag: "🔵" },
  "leicester":         { slug: "leicester",          id: 46,   leagueSlug: "premier-league", nameEn: "Leicester",          nameKo: "레스터 시티",           flag: "🔵" },
  "southampton":       { slug: "southampton",        id: 41,   leagueSlug: "premier-league", nameEn: "Southampton",        nameKo: "사우샘프턴",            flag: "🔴" },
  // ── La Liga (20팀) ───────────────────────────────────────────────────────────
  "real-madrid":       { slug: "real-madrid",        id: 541,  leagueSlug: "la-liga",        nameEn: "Real Madrid",        nameKo: "레알 마드리드",         flag: "⚪" },
  "barcelona":         { slug: "barcelona",          id: 529,  leagueSlug: "la-liga",        nameEn: "Barcelona",          nameKo: "바르셀로나",            flag: "🔵" },
  "atletico-madrid":   { slug: "atletico-madrid",    id: 530,  leagueSlug: "la-liga",        nameEn: "Atletico Madrid",    nameKo: "아틀레티코 마드리드",   flag: "🔴" },
  "sevilla":           { slug: "sevilla",            id: 536,  leagueSlug: "la-liga",        nameEn: "Sevilla",            nameKo: "세비야",               flag: "⚪" },
  "real-betis":        { slug: "real-betis",         id: 543,  leagueSlug: "la-liga",        nameEn: "Real Betis",         nameKo: "레알 베티스",           flag: "🟢" },
  "athletic-club":     { slug: "athletic-club",      id: 531,  leagueSlug: "la-liga",        nameEn: "Athletic Club",      nameKo: "아틀레틱 빌바오",       flag: "🔴" },
  "valencia":          { slug: "valencia",           id: 532,  leagueSlug: "la-liga",        nameEn: "Valencia",           nameKo: "발렌시아",             flag: "⚪" },
  "real-sociedad":     { slug: "real-sociedad",      id: 548,  leagueSlug: "la-liga",        nameEn: "Real Sociedad",      nameKo: "레알 소시에다드",       flag: "🔵" },
  "osasuna":           { slug: "osasuna",            id: 727,  leagueSlug: "la-liga",        nameEn: "Osasuna",            nameKo: "오사수나",             flag: "🔴" },
  "girona":            { slug: "girona",             id: 547,  leagueSlug: "la-liga",        nameEn: "Girona",             nameKo: "지로나",               flag: "🔴" },
  "villarreal":        { slug: "villarreal",         id: 533,  leagueSlug: "la-liga",        nameEn: "Villarreal",         nameKo: "비야레알",             flag: "🟡" },
  "getafe":            { slug: "getafe",             id: 546,  leagueSlug: "la-liga",        nameEn: "Getafe",             nameKo: "헤타페",               flag: "🔵" },
  "rayo-vallecano":    { slug: "rayo-vallecano",     id: 728,  leagueSlug: "la-liga",        nameEn: "Rayo Vallecano",     nameKo: "라요 바예카노",         flag: "🔴" },
  "las-palmas":        { slug: "las-palmas",         id: 736,  leagueSlug: "la-liga",        nameEn: "Las Palmas",         nameKo: "라스 팔마스",           flag: "🟡" },
  "celta-vigo":        { slug: "celta-vigo",         id: 538,  leagueSlug: "la-liga",        nameEn: "Celta Vigo",         nameKo: "셀타 비고",            flag: "🔵" },
  "espanyol":          { slug: "espanyol",           id: 540,  leagueSlug: "la-liga",        nameEn: "Espanyol",           nameKo: "에스파뇰",             flag: "🔵" },
  "mallorca":          { slug: "mallorca",           id: 723,  leagueSlug: "la-liga",        nameEn: "Mallorca",           nameKo: "마요르카",             flag: "🔴" },
  "valladolid":        { slug: "valladolid",         id: 718,  leagueSlug: "la-liga",        nameEn: "Valladolid",         nameKo: "바야돌리드",            flag: "🟣" },
  "alaves":            { slug: "alaves",             id: 545,  leagueSlug: "la-liga",        nameEn: "Alaves",             nameKo: "알라베스",             flag: "🔵" },
  "leganes":           { slug: "leganes",            id: 719,  leagueSlug: "la-liga",        nameEn: "Leganés",            nameKo: "레가네스",             flag: "🔵" },
  // ── Bundesliga (18팀) ────────────────────────────────────────────────────────
  "bayern-munich":     { slug: "bayern-munich",      id: 157,  leagueSlug: "bundesliga",     nameEn: "Bayern Munich",      nameKo: "바이에른 뮌헨",         flag: "🔴" },
  "dortmund":          { slug: "dortmund",           id: 165,  leagueSlug: "bundesliga",     nameEn: "Borussia Dortmund",  nameKo: "보루시아 도르트문트",   flag: "🟡" },
  "bayer-leverkusen":  { slug: "bayer-leverkusen",   id: 168,  leagueSlug: "bundesliga",     nameEn: "Bayer Leverkusen",   nameKo: "바이어 레버쿠젠",       flag: "🔴" },
  "rb-leipzig":        { slug: "rb-leipzig",         id: 173,  leagueSlug: "bundesliga",     nameEn: "RB Leipzig",         nameKo: "RB 라이프치히",         flag: "🔵" },
  "frankfurt":         { slug: "frankfurt",          id: 169,  leagueSlug: "bundesliga",     nameEn: "Eintracht Frankfurt",nameKo: "프랑크푸르트",          flag: "🔴" },
  "stuttgart":         { slug: "stuttgart",          id: 172,  leagueSlug: "bundesliga",     nameEn: "Stuttgart",          nameKo: "슈투트가르트",          flag: "🔴" },
  "wolfsburg":         { slug: "wolfsburg",          id: 161,  leagueSlug: "bundesliga",     nameEn: "Wolfsburg",          nameKo: "볼프스부르크",          flag: "🟢" },
  "hoffenheim":        { slug: "hoffenheim",         id: 167,  leagueSlug: "bundesliga",     nameEn: "Hoffenheim",         nameKo: "호펜하임",             flag: "🔵" },
  "gladbach":          { slug: "gladbach",           id: 163,  leagueSlug: "bundesliga",     nameEn: "B. Mönchengladbach", nameKo: "묀헨글라트바흐",        flag: "🟢" },
  "freiburg":          { slug: "freiburg",           id: 160,  leagueSlug: "bundesliga",     nameEn: "Freiburg",           nameKo: "프라이부르크",          flag: "🔴" },
  "union-berlin":      { slug: "union-berlin",       id: 182,  leagueSlug: "bundesliga",     nameEn: "Union Berlin",       nameKo: "우니온 베를린",         flag: "🔴" },
  "mainz":             { slug: "mainz",              id: 164,  leagueSlug: "bundesliga",     nameEn: "Mainz",              nameKo: "마인츠",               flag: "🔴" },
  "augsburg":          { slug: "augsburg",           id: 170,  leagueSlug: "bundesliga",     nameEn: "Augsburg",           nameKo: "아우크스부르크",        flag: "🟢" },
  "werder-bremen":     { slug: "werder-bremen",      id: 162,  leagueSlug: "bundesliga",     nameEn: "Werder Bremen",      nameKo: "베르더 브레멘",         flag: "🟢" },
  "heidenheim":        { slug: "heidenheim",         id: 180,  leagueSlug: "bundesliga",     nameEn: "Heidenheim",         nameKo: "하이덴하임",            flag: "🔴" },
  "bochum":            { slug: "bochum",             id: 176,  leagueSlug: "bundesliga",     nameEn: "Bochum",             nameKo: "보훔",                 flag: "🔵" },
  "st-pauli":          { slug: "st-pauli",           id: 178,  leagueSlug: "bundesliga",     nameEn: "St. Pauli",          nameKo: "장크트파울리",          flag: "🟤" },
  "kiel":              { slug: "kiel",               id: 174,  leagueSlug: "bundesliga",     nameEn: "Holstein Kiel",      nameKo: "홀슈타인 킬",           flag: "🔵" },
  // ── Serie A (20팀) ───────────────────────────────────────────────────────────
  "inter-milan":       { slug: "inter-milan",        id: 505,  leagueSlug: "serie-a",        nameEn: "Inter Milan",        nameKo: "인터 밀란",             flag: "🔵" },
  "ac-milan":          { slug: "ac-milan",           id: 489,  leagueSlug: "serie-a",        nameEn: "AC Milan",           nameKo: "AC 밀란",               flag: "🔴" },
  "juventus":          { slug: "juventus",           id: 496,  leagueSlug: "serie-a",        nameEn: "Juventus",           nameKo: "유벤투스",              flag: "⚫" },
  "napoli":            { slug: "napoli",             id: 492,  leagueSlug: "serie-a",        nameEn: "Napoli",             nameKo: "나폴리",               flag: "🔵" },
  "as-roma":           { slug: "as-roma",            id: 497,  leagueSlug: "serie-a",        nameEn: "AS Roma",            nameKo: "AS 로마",               flag: "🔴" },
  "lazio":             { slug: "lazio",              id: 487,  leagueSlug: "serie-a",        nameEn: "Lazio",              nameKo: "라치오",               flag: "🔵" },
  "atalanta":          { slug: "atalanta",           id: 499,  leagueSlug: "serie-a",        nameEn: "Atalanta",           nameKo: "아탈란타",             flag: "🔵" },
  "fiorentina":        { slug: "fiorentina",         id: 502,  leagueSlug: "serie-a",        nameEn: "Fiorentina",         nameKo: "피오렌티나",            flag: "🟣" },
  "bologna":           { slug: "bologna",            id: 500,  leagueSlug: "serie-a",        nameEn: "Bologna",            nameKo: "볼로냐",               flag: "🔴" },
  "torino":            { slug: "torino",             id: 503,  leagueSlug: "serie-a",        nameEn: "Torino",             nameKo: "토리노",               flag: "🔴" },
  "verona":            { slug: "verona",             id: 504,  leagueSlug: "serie-a",        nameEn: "Verona",             nameKo: "헬라스 베로나",         flag: "🟡" },
  "empoli":            { slug: "empoli",             id: 511,  leagueSlug: "serie-a",        nameEn: "Empoli",             nameKo: "엠폴리",               flag: "🔵" },
  "cagliari":          { slug: "cagliari",           id: 490,  leagueSlug: "serie-a",        nameEn: "Cagliari",           nameKo: "칼리아리",             flag: "🔴" },
  "genoa":             { slug: "genoa",              id: 495,  leagueSlug: "serie-a",        nameEn: "Genoa",              nameKo: "제노아",               flag: "🔴" },
  "lecce":             { slug: "lecce",              id: 867,  leagueSlug: "serie-a",        nameEn: "Lecce",              nameKo: "레체",                 flag: "🟡" },
  "udinese":           { slug: "udinese",            id: 494,  leagueSlug: "serie-a",        nameEn: "Udinese",            nameKo: "우디네세",             flag: "⚫" },
  "parma":             { slug: "parma",              id: 493,  leagueSlug: "serie-a",        nameEn: "Parma",              nameKo: "파르마",               flag: "🟡" },
  "venezia":           { slug: "venezia",            id: 517,  leagueSlug: "serie-a",        nameEn: "Venezia",            nameKo: "베네치아",             flag: "🟠" },
  "monza":             { slug: "monza",              id: 1579, leagueSlug: "serie-a",        nameEn: "Monza",              nameKo: "몬차",                 flag: "⚪" },
  "como":              { slug: "como",               id: 4052, leagueSlug: "serie-a",        nameEn: "Como",               nameKo: "코모",                 flag: "🔵" },
  // ── Ligue 1 (18팀) ───────────────────────────────────────────────────────────
  "paris-sg":          { slug: "paris-sg",           id: 85,   leagueSlug: "ligue-1",        nameEn: "Paris SG",           nameKo: "파리 생제르맹",         flag: "🔵" },
  "monaco":            { slug: "monaco",             id: 91,   leagueSlug: "ligue-1",        nameEn: "Monaco",             nameKo: "모나코",               flag: "🔴" },
  "marseille":         { slug: "marseille",          id: 81,   leagueSlug: "ligue-1",        nameEn: "Marseille",          nameKo: "마르세유",             flag: "🔵" },
  "lyon":              { slug: "lyon",               id: 80,   leagueSlug: "ligue-1",        nameEn: "Lyon",               nameKo: "리옹",                 flag: "🔴" },
  "lille":             { slug: "lille",              id: 79,   leagueSlug: "ligue-1",        nameEn: "Lille",              nameKo: "릴",                   flag: "🔴" },
  "lens":              { slug: "lens",               id: 116,  leagueSlug: "ligue-1",        nameEn: "Lens",               nameKo: "렝스",                 flag: "🟡" },
  "rennes":            { slug: "rennes",             id: 94,   leagueSlug: "ligue-1",        nameEn: "Rennes",             nameKo: "렌",                   flag: "🔴" },
  "nice":              { slug: "nice",               id: 84,   leagueSlug: "ligue-1",        nameEn: "Nice",               nameKo: "니스",                 flag: "🔴" },
  "toulouse":          { slug: "toulouse",           id: 93,   leagueSlug: "ligue-1",        nameEn: "Toulouse",           nameKo: "툴루즈",               flag: "🟣" },
  "brest":             { slug: "brest",              id: 191,  leagueSlug: "ligue-1",        nameEn: "Brest",              nameKo: "브레스트",             flag: "🔴" },
  "nantes":            { slug: "nantes",             id: 83,   leagueSlug: "ligue-1",        nameEn: "Nantes",             nameKo: "낭트",                 flag: "🟡" },
  "reims":             { slug: "reims",              id: 96,   leagueSlug: "ligue-1",        nameEn: "Reims",              nameKo: "랭스",                 flag: "🔴" },
  "strasbourg":        { slug: "strasbourg",         id: 95,   leagueSlug: "ligue-1",        nameEn: "Strasbourg",         nameKo: "스트라스부르",          flag: "🔵" },
  "montpellier":       { slug: "montpellier",        id: 82,   leagueSlug: "ligue-1",        nameEn: "Montpellier",        nameKo: "몽펠리에",             flag: "🟠" },
  "auxerre":           { slug: "auxerre",            id: 78,   leagueSlug: "ligue-1",        nameEn: "Auxerre",            nameKo: "오세르",               flag: "🔴" },
  "saint-etienne":     { slug: "saint-etienne",      id: 97,   leagueSlug: "ligue-1",        nameEn: "Saint-Etienne",      nameKo: "생테티엔",             flag: "🟢" },
  "le-havre":          { slug: "le-havre",           id: 1100, leagueSlug: "ligue-1",        nameEn: "Le Havre",           nameKo: "르아브르",             flag: "🔵" },
  "angers":            { slug: "angers",             id: 1076, leagueSlug: "ligue-1",        nameEn: "Angers",             nameKo: "앙제",                 flag: "⚫" },
  // ── Eredivisie (18팀) ────────────────────────────────────────────────────────
  "ajax":              { slug: "ajax",               id: 194,  leagueSlug: "eredivisie",     nameEn: "Ajax",               nameKo: "아약스",               flag: "🔴" },
  "psv":               { slug: "psv",                id: 231,  leagueSlug: "eredivisie",     nameEn: "PSV",                nameKo: "PSV",                  flag: "🔴" },
  "feyenoord":         { slug: "feyenoord",          id: 197,  leagueSlug: "eredivisie",     nameEn: "Feyenoord",          nameKo: "페예노르트",            flag: "🔴" },
  "az-alkmaar":        { slug: "az-alkmaar",         id: 193,  leagueSlug: "eredivisie",     nameEn: "AZ Alkmaar",         nameKo: "AZ 알크마르",           flag: "🔴" },
  "twente":            { slug: "twente",             id: 198,  leagueSlug: "eredivisie",     nameEn: "Twente",             nameKo: "트벤터",               flag: "🔴" },
  "utrecht":           { slug: "utrecht",            id: 200,  leagueSlug: "eredivisie",     nameEn: "Utrecht",            nameKo: "위트레흐트",            flag: "🔴" },
  "heerenveen":        { slug: "heerenveen",         id: 196,  leagueSlug: "eredivisie",     nameEn: "Heerenveen",         nameKo: "헤이런베인",            flag: "🔵" },
  "groningen":         { slug: "groningen",          id: 204,  leagueSlug: "eredivisie",     nameEn: "Groningen",          nameKo: "흐로닝언",              flag: "🟢" },
  "sparta-rotterdam":  { slug: "sparta-rotterdam",   id: 199,  leagueSlug: "eredivisie",     nameEn: "Sparta Rotterdam",   nameKo: "스파르타 로테르담",     flag: "🔴" },
  "go-ahead-eagles":   { slug: "go-ahead-eagles",    id: 202,  leagueSlug: "eredivisie",     nameEn: "Go Ahead Eagles",    nameKo: "고 어헤드 이글스",      flag: "🟡" },
  "almere":            { slug: "almere",             id: 1895, leagueSlug: "eredivisie",     nameEn: "Almere City",        nameKo: "알메러 시티",           flag: "🔵" },
  "nac-breda":         { slug: "nac-breda",          id: 203,  leagueSlug: "eredivisie",     nameEn: "NAC Breda",          nameKo: "NAC 브레다",            flag: "🟡" },
  "pec-zwolle":        { slug: "pec-zwolle",         id: 205,  leagueSlug: "eredivisie",     nameEn: "PEC Zwolle",         nameKo: "PEC 즈볼러",            flag: "🔵" },
  // ── Primeira Liga (18팀) ─────────────────────────────────────────────────────
  "porto":             { slug: "porto",              id: 212,  leagueSlug: "primeira-liga",  nameEn: "Porto",              nameKo: "포르투",               flag: "🔵" },
  "benfica":           { slug: "benfica",            id: 211,  leagueSlug: "primeira-liga",  nameEn: "Benfica",            nameKo: "벤피카",               flag: "🔴" },
  "sporting-cp":       { slug: "sporting-cp",        id: 228,  leagueSlug: "primeira-liga",  nameEn: "Sporting CP",        nameKo: "스포르팅 CP",           flag: "🟢" },
  "braga":             { slug: "braga",              id: 217,  leagueSlug: "primeira-liga",  nameEn: "Braga",              nameKo: "브라가",               flag: "🔴" },
  "vitoria-sc":        { slug: "vitoria-sc",         id: 227,  leagueSlug: "primeira-liga",  nameEn: "Vitória SC",         nameKo: "비토리아 SC",           flag: "🟢" },
  "v-guimaraes":       { slug: "v-guimaraes",        id: 232,  leagueSlug: "primeira-liga",  nameEn: "V. Guimarães",       nameKo: "V. 기마랑이스",         flag: "🔵" },
  "farense":           { slug: "farense",            id: 213,  leagueSlug: "primeira-liga",  nameEn: "Farense",            nameKo: "파렌시",               flag: "🔴" },
  "aves":              { slug: "aves",               id: 225,  leagueSlug: "primeira-liga",  nameEn: "Aves",               nameKo: "아베스",               flag: "🔴" },
  "gil-vicente":       { slug: "gil-vicente",        id: 222,  leagueSlug: "primeira-liga",  nameEn: "Gil Vicente",        nameKo: "질 비센터",            flag: "⚫" },
  "moreirense":        { slug: "moreirense",         id: 216,  leagueSlug: "primeira-liga",  nameEn: "Moreirense",         nameKo: "모레이렌세",            flag: "🟢" },
  "boavista":          { slug: "boavista",           id: 215,  leagueSlug: "primeira-liga",  nameEn: "Boavista",           nameKo: "보아비스타",            flag: "⚫" },
  "famalicao":         { slug: "famalicao",          id: 221,  leagueSlug: "primeira-liga",  nameEn: "Famalicão",          nameKo: "파말리캉",             flag: "🔵" },
  // ── Saudi Pro League (16팀) ──────────────────────────────────────────────────
  "al-hilal":          { slug: "al-hilal",           id: 2912, leagueSlug: "saudi-pro-league", nameEn: "Al-Hilal",         nameKo: "알 힐랄",              flag: "🔵" },
  "al-nassr":          { slug: "al-nassr",           id: 2913, leagueSlug: "saudi-pro-league", nameEn: "Al-Nassr",         nameKo: "알 나스르",            flag: "🟡" },
  "al-ittihad":        { slug: "al-ittihad",         id: 2921, leagueSlug: "saudi-pro-league", nameEn: "Al-Ittihad",       nameKo: "알 이티하드",          flag: "🟡" },
  "al-ahli":           { slug: "al-ahli",            id: 2914, leagueSlug: "saudi-pro-league", nameEn: "Al-Ahli",          nameKo: "알 아흘리",            flag: "🟢" },
  "al-qadsiah":        { slug: "al-qadsiah",         id: 2917, leagueSlug: "saudi-pro-league", nameEn: "Al-Qadsiah",       nameKo: "알 카디시아",          flag: "🔵" },
  "al-faisaly":        { slug: "al-faisaly",         id: 2916, leagueSlug: "saudi-pro-league", nameEn: "Al-Faisaly",       nameKo: "알 파이살리",          flag: "🟢" },
  "al-shabbab":        { slug: "al-shabbab",         id: 2918, leagueSlug: "saudi-pro-league", nameEn: "Al-Shabbab",       nameKo: "알 샤밥",              flag: "🔴" },
  "al-taawoun":        { slug: "al-taawoun",         id: 2919, leagueSlug: "saudi-pro-league", nameEn: "Al-Taawoun",       nameKo: "알 타아원",            flag: "🟡" },
  "al-ettifaq":        { slug: "al-ettifaq",         id: 2920, leagueSlug: "saudi-pro-league", nameEn: "Al-Ettifaq",       nameKo: "알 에티파크",          flag: "🟢" },
  "al-shabab-saudi":   { slug: "al-shabab-saudi",    id: 2923, leagueSlug: "saudi-pro-league", nameEn: "Al-Shabab",        nameKo: "알 샤밥 (사우디)",     flag: "🔴" },
  "al-riyadh":         { slug: "al-riyadh",          id: 2926, leagueSlug: "saudi-pro-league", nameEn: "Al-Riyadh",        nameKo: "알 리야드",            flag: "🟢" },
  "al-wehda":          { slug: "al-wehda",           id: 2927, leagueSlug: "saudi-pro-league", nameEn: "Al-Wehda",         nameKo: "알 웨흐다",            flag: "🟢" },
  // ── MLS (29팀) ───────────────────────────────────────────────────────────────
  "inter-miami":       { slug: "inter-miami",        id: 1602, leagueSlug: "mls",           nameEn: "Inter Miami",        nameKo: "인터 마이애미",         flag: "🩷" },
  "la-galaxy":         { slug: "la-galaxy",          id: 1611, leagueSlug: "mls",           nameEn: "LA Galaxy",          nameKo: "LA 갤럭시",             flag: "🔵" },
  "nycfc":             { slug: "nycfc",              id: 1605, leagueSlug: "mls",           nameEn: "NYC FC",             nameKo: "뉴욕 시티 FC",          flag: "🔵" },
  "seattle-sounders":  { slug: "seattle-sounders",   id: 1614, leagueSlug: "mls",           nameEn: "Seattle Sounders",   nameKo: "시애틀 사운더스",       flag: "🟢" },
  "portland-timbers":  { slug: "portland-timbers",   id: 1615, leagueSlug: "mls",           nameEn: "Portland Timbers",   nameKo: "포틀랜드 팀버스",       flag: "🟢" },
  "atlanta-united":    { slug: "atlanta-united",     id: 1601, leagueSlug: "mls",           nameEn: "Atlanta United",     nameKo: "애틀랜타 유나이티드",   flag: "🔴" },
  "chicago-fire":      { slug: "chicago-fire",       id: 1607, leagueSlug: "mls",           nameEn: "Chicago Fire",       nameKo: "시카고 파이어",         flag: "🔴" },
  "ny-red-bulls":      { slug: "ny-red-bulls",       id: 1608, leagueSlug: "mls",           nameEn: "NY Red Bulls",       nameKo: "뉴욕 레드불스",         flag: "🔴" },
  "lafc":              { slug: "lafc",               id: 1612, leagueSlug: "mls",           nameEn: "LAFC",               nameKo: "LAFC",                 flag: "⚫" },
  "columbus-crew":     { slug: "columbus-crew",      id: 1604, leagueSlug: "mls",           nameEn: "Columbus Crew",      nameKo: "콜럼버스 크루",         flag: "🟡" },
  "fc-cincinnati":     { slug: "fc-cincinnati",      id: 16053, leagueSlug: "mls",          nameEn: "FC Cincinnati",      nameKo: "FC 신시내티",           flag: "🔵" },
  // ── K League 1 (12팀) ────────────────────────────────────────────────────────
  "jeonbuk":           { slug: "jeonbuk",            id: 2742, leagueSlug: "k-league-1",    nameEn: "Jeonbuk Hyundai",    nameKo: "전북 현대",             flag: "🟢" },
  "ulsan":             { slug: "ulsan",              id: 2730, leagueSlug: "k-league-1",    nameEn: "Ulsan HD",           nameKo: "울산 HD",               flag: "🔵" },
  "seoulfc":           { slug: "seoulfc",            id: 2743, leagueSlug: "k-league-1",    nameEn: "Seoul FC",           nameKo: "서울 FC",               flag: "🔵" },
  "suwon":             { slug: "suwon",              id: 2740, leagueSlug: "k-league-1",    nameEn: "Suwon Samsung",      nameKo: "수원 삼성",             flag: "🔵" },
  "pohang":            { slug: "pohang",             id: 2738, leagueSlug: "k-league-1",    nameEn: "Pohang Steelers",    nameKo: "포항 스틸러스",         flag: "🔴" },
  "daegu":             { slug: "daegu",              id: 2729, leagueSlug: "k-league-1",    nameEn: "Daegu FC",           nameKo: "대구 FC",               flag: "🔵" },
  "incheon":           { slug: "incheon",            id: 2744, leagueSlug: "k-league-1",    nameEn: "Incheon United",     nameKo: "인천 유나이티드",       flag: "🔵" },
  "gwangju":           { slug: "gwangju",            id: 2741, leagueSlug: "k-league-1",    nameEn: "Gwangju FC",         nameKo: "광주 FC",               flag: "🟡" },
  "jeju":              { slug: "jeju",               id: 2745, leagueSlug: "k-league-1",    nameEn: "Jeju United",        nameKo: "제주 유나이티드",       flag: "🟠" },
  "gimcheon":          { slug: "gimcheon",           id: 2736, leagueSlug: "k-league-1",    nameEn: "Gimcheon Sangmu",    nameKo: "김천 상무",             flag: "🔵" },
  "seongnam":          { slug: "seongnam",           id: 2739, leagueSlug: "k-league-1",    nameEn: "Seongnam FC",        nameKo: "성남 FC",               flag: "🔵" },
  "gangwon":           { slug: "gangwon",            id: 2746, leagueSlug: "k-league-1",    nameEn: "Gangwon FC",         nameKo: "강원 FC",               flag: "🔵" },
  // ── J1 League (18팀) ─────────────────────────────────────────────────────────
  "kashima":           { slug: "kashima",            id: 311,  leagueSlug: "j1-league",     nameEn: "Kashima Antlers",    nameKo: "가시마 앤틀러스",       flag: "🔴" },
  "urawa-reds":        { slug: "urawa-reds",         id: 314,  leagueSlug: "j1-league",     nameEn: "Urawa Reds",         nameKo: "우라와 레즈",           flag: "🔴" },
  "gamba-osaka":       { slug: "gamba-osaka",        id: 309,  leagueSlug: "j1-league",     nameEn: "Gamba Osaka",        nameKo: "감바 오사카",           flag: "🔵" },
  "vissel-kobe":       { slug: "vissel-kobe",        id: 319,  leagueSlug: "j1-league",     nameEn: "Vissel Kobe",        nameKo: "비셀 고베",             flag: "🔴" },
  "yokohama-fm":       { slug: "yokohama-fm",        id: 316,  leagueSlug: "j1-league",     nameEn: "Yokohama F. Marinos",nameKo: "요코하마 F. 마리노스",  flag: "🔵" },
  "cerezo-osaka":      { slug: "cerezo-osaka",       id: 315,  leagueSlug: "j1-league",     nameEn: "Cerezo Osaka",       nameKo: "세레소 오사카",         flag: "🩷" },
  "kawasaki":          { slug: "kawasaki",           id: 318,  leagueSlug: "j1-league",     nameEn: "Kawasaki Frontale",  nameKo: "가와사키 프론탈레",     flag: "🔵" },
  "nagoya-grampus":    { slug: "nagoya-grampus",     id: 312,  leagueSlug: "j1-league",     nameEn: "Nagoya Grampus",     nameKo: "나고야 그램퍼스",       flag: "🔴" },
  "sanfrecce":         { slug: "sanfrecce",          id: 313,  leagueSlug: "j1-league",     nameEn: "Sanfrecce Hiroshima",nameKo: "산프레체 히로시마",     flag: "🟣" },
  "sagan-tosu":        { slug: "sagan-tosu",         id: 317,  leagueSlug: "j1-league",     nameEn: "Sagan Tosu",         nameKo: "사간 도스",             flag: "🔵" },
  "consadole":         { slug: "consadole",          id: 308,  leagueSlug: "j1-league",     nameEn: "Consadole Sapporo",  nameKo: "콘사돌레 삿포로",       flag: "🔴" },
  "avispa-fukuoka":    { slug: "avispa-fukuoka",     id: 320,  leagueSlug: "j1-league",     nameEn: "Avispa Fukuoka",     nameKo: "아비스파 후쿠오카",     flag: "🔵" },
  // ── Liga MX (18팀) ───────────────────────────────────────────────────────────
  "club-america":      { slug: "club-america",       id: 1951, leagueSlug: "liga-mx",       nameEn: "Club América",       nameKo: "클럽 아메리카",         flag: "🟡" },
  "chivas":            { slug: "chivas",             id: 1953, leagueSlug: "liga-mx",       nameEn: "Chivas Guadalajara", nameKo: "치바스 과달라하라",     flag: "🔴" },
  "cruz-azul":         { slug: "cruz-azul",          id: 1952, leagueSlug: "liga-mx",       nameEn: "Cruz Azul",          nameKo: "크루스 아술",           flag: "🔵" },
  "tigres":            { slug: "tigres",             id: 1954, leagueSlug: "liga-mx",       nameEn: "Tigres UANL",        nameKo: "티그레스 UANL",         flag: "🟡" },
  "monterrey":         { slug: "monterrey",          id: 1955, leagueSlug: "liga-mx",       nameEn: "CF Monterrey",       nameKo: "CF 몬테레이",           flag: "🔵" },
  "toluca":            { slug: "toluca",             id: 1956, leagueSlug: "liga-mx",       nameEn: "Toluca",             nameKo: "톨루카",               flag: "🔴" },
  "pumas":             { slug: "pumas",              id: 1957, leagueSlug: "liga-mx",       nameEn: "Pumas UNAM",         nameKo: "푸마스 UNAM",           flag: "🔵" },
  "santos-laguna":     { slug: "santos-laguna",      id: 1959, leagueSlug: "liga-mx",       nameEn: "Santos Laguna",      nameKo: "산토스 라구나",         flag: "🟢" },
  "atlas":             { slug: "atlas",              id: 1958, leagueSlug: "liga-mx",       nameEn: "Atlas",              nameKo: "아틀라스",             flag: "🔴" },
  "leon":              { slug: "leon",               id: 1960, leagueSlug: "liga-mx",       nameEn: "León",               nameKo: "레온",                 flag: "🟢" },
  // ── Süper Lig (19팀) ─────────────────────────────────────────────────────────
  "galatasaray":       { slug: "galatasaray",        id: 645,  leagueSlug: "super-lig",     nameEn: "Galatasaray",        nameKo: "갈라타사라이",          flag: "🔴" },
  "fenerbahce":        { slug: "fenerbahce",         id: 611,  leagueSlug: "super-lig",     nameEn: "Fenerbahçe",         nameKo: "페네르바체",            flag: "🟡" },
  "besiktas":          { slug: "besiktas",           id: 614,  leagueSlug: "super-lig",     nameEn: "Beşiktaş",           nameKo: "베식타스",             flag: "⚫" },
  "trabzonspor":       { slug: "trabzonspor",        id: 641,  leagueSlug: "super-lig",     nameEn: "Trabzonspor",        nameKo: "트라브존스포르",        flag: "🔴" },
  "basaksehir":        { slug: "basaksehir",         id: 643,  leagueSlug: "super-lig",     nameEn: "İstanbul Başakşehir",nameKo: "이스탄불 바샥셰히르",   flag: "🟠" },
  "sivasspor":         { slug: "sivasspor",          id: 647,  leagueSlug: "super-lig",     nameEn: "Sivasspor",          nameKo: "시바스스포르",          flag: "🔴" },
  "konyaspor":         { slug: "konyaspor",          id: 651,  leagueSlug: "super-lig",     nameEn: "Konyaspor",          nameKo: "코냐스포르",            flag: "🟢" },
  "kasimpasa":         { slug: "kasimpasa",          id: 653,  leagueSlug: "super-lig",     nameEn: "Kasımpaşa",          nameKo: "카슴파샤",             flag: "🔵" },
  // ── Brasileirão (20팀) ───────────────────────────────────────────────────────
  "flamengo":          { slug: "flamengo",           id: 127,  leagueSlug: "brasileirao",   nameEn: "Flamengo",           nameKo: "플라멩고",             flag: "🔴" },
  "palmeiras":         { slug: "palmeiras",          id: 121,  leagueSlug: "brasileirao",   nameEn: "Palmeiras",          nameKo: "팔메이라스",            flag: "🟢" },
  "corinthians":       { slug: "corinthians",        id: 131,  leagueSlug: "brasileirao",   nameEn: "Corinthians",        nameKo: "코린치안스",            flag: "⚫" },
  "sao-paulo":         { slug: "sao-paulo",          id: 126,  leagueSlug: "brasileirao",   nameEn: "São Paulo",          nameKo: "상파울루",             flag: "🔴" },
  "atletico-mg":       { slug: "atletico-mg",        id: 1062, leagueSlug: "brasileirao",   nameEn: "Atlético-MG",        nameKo: "아틀레티코 미네이루",   flag: "⚫" },
  "fluminense":        { slug: "fluminense",         id: 119,  leagueSlug: "brasileirao",   nameEn: "Fluminense",         nameKo: "플루미넨시",            flag: "🔴" },
  "internacional":     { slug: "internacional",      id: 118,  leagueSlug: "brasileirao",   nameEn: "Internacional",      nameKo: "인테르나시오날",        flag: "🔴" },
  "santos":            { slug: "santos",             id: 123,  leagueSlug: "brasileirao",   nameEn: "Santos",             nameKo: "산투스",               flag: "⚫" },
  "botafogo":          { slug: "botafogo",           id: 1297, leagueSlug: "brasileirao",   nameEn: "Botafogo",           nameKo: "보타포구",             flag: "⚫" },
  "cruzeiro":          { slug: "cruzeiro",           id: 1625, leagueSlug: "brasileirao",   nameEn: "Cruzeiro",           nameKo: "크루제이루",            flag: "🔵" },
  // ── Scottish Premiership (12팀) ──────────────────────────────────────────────
  "celtic":            { slug: "celtic",             id: 264,  leagueSlug: "scottish-premiership", nameEn: "Celtic",       nameKo: "셀틱",                 flag: "🟢" },
  "rangers":           { slug: "rangers",            id: 267,  leagueSlug: "scottish-premiership", nameEn: "Rangers",      nameKo: "레인저스",             flag: "🔵" },
  "hearts":            { slug: "hearts",             id: 257,  leagueSlug: "scottish-premiership", nameEn: "Hearts",       nameKo: "하츠",                 flag: "🔴" },
  "hibernian":         { slug: "hibernian",          id: 258,  leagueSlug: "scottish-premiership", nameEn: "Hibernian",    nameKo: "히베르니안",            flag: "🟢" },
  "aberdeen":          { slug: "aberdeen",           id: 259,  leagueSlug: "scottish-premiership", nameEn: "Aberdeen",     nameKo: "애버딘",               flag: "🔴" },
  "motherwell":        { slug: "motherwell",         id: 262,  leagueSlug: "scottish-premiership", nameEn: "Motherwell",   nameKo: "머더웰",               flag: "🔴" },
  "st-mirren":         { slug: "st-mirren",          id: 265,  leagueSlug: "scottish-premiership", nameEn: "St. Mirren",   nameKo: "성 미렌",              flag: "⚫" },
  "dundee-utd":        { slug: "dundee-utd",         id: 260,  leagueSlug: "scottish-premiership", nameEn: "Dundee Utd",   nameKo: "던디 유나이티드",       flag: "🟠" },
};

// ─── Pre-grouped constant (zero runtime cost) ──────────────────────────────────
// Built once at module initialisation — imported directly by the Team Hub page
// so there is no filtering logic that can silently return an empty array.

const ALL_ENTRIES = Object.values(TEAM_REGISTRY);

export const TEAMS_BY_LEAGUE: Record<string, TeamEntry[]> = {
  "premier-league":        ALL_ENTRIES.filter((t) => t.leagueSlug === "premier-league"),
  "la-liga":               ALL_ENTRIES.filter((t) => t.leagueSlug === "la-liga"),
  "bundesliga":            ALL_ENTRIES.filter((t) => t.leagueSlug === "bundesliga"),
  "serie-a":               ALL_ENTRIES.filter((t) => t.leagueSlug === "serie-a"),
  "ligue-1":               ALL_ENTRIES.filter((t) => t.leagueSlug === "ligue-1"),
  "champions-league":      ALL_ENTRIES.filter((t) => t.leagueSlug === "champions-league"),
  "europa-league":         ALL_ENTRIES.filter((t) => t.leagueSlug === "europa-league"),
  "eredivisie":            ALL_ENTRIES.filter((t) => t.leagueSlug === "eredivisie"),
  "primeira-liga":         ALL_ENTRIES.filter((t) => t.leagueSlug === "primeira-liga"),
  "saudi-pro-league":      ALL_ENTRIES.filter((t) => t.leagueSlug === "saudi-pro-league"),
  "mls":                   ALL_ENTRIES.filter((t) => t.leagueSlug === "mls"),
  "k-league-1":            ALL_ENTRIES.filter((t) => t.leagueSlug === "k-league-1"),
  "j1-league":             ALL_ENTRIES.filter((t) => t.leagueSlug === "j1-league"),
  "liga-mx":               ALL_ENTRIES.filter((t) => t.leagueSlug === "liga-mx"),
  "super-lig":             ALL_ENTRIES.filter((t) => t.leagueSlug === "super-lig"),
  "brasileirao":           ALL_ENTRIES.filter((t) => t.leagueSlug === "brasileirao"),
  "scottish-premiership":  ALL_ENTRIES.filter((t) => t.leagueSlug === "scottish-premiership"),
};

export const VALID_TEAM_SLUGS = Object.keys(TEAM_REGISTRY);

// ---------------------------------------------------------------------------
// Name-based Korean lookup — 100+ teams across EPL / La Liga / Bundesliga /
// Serie A / UCL and their common API name variants / aliases.
// ---------------------------------------------------------------------------

export const TEAM_NAME_KO: Record<string, string> = {
  // EPL
  "Arsenal":                        "아스널",
  "Manchester City":                "맨체스터 시티",
  "Manchester United":              "맨체스터 유나이티드",
  "Liverpool":                      "리버풀",
  "Chelsea":                        "첼시",
  "Tottenham":                      "토트넘",
  "Newcastle":                      "뉴캐슬",
  "Newcastle United":               "뉴캐슬",
  "Aston Villa":                    "아스턴 빌라",
  "Brentford":                      "브렌트퍼드",
  "Bournemouth":                    "본머스",
  "AFC Bournemouth":                "본머스",
  "Brighton":                       "브라이턴",
  "Brighton & Hove Albion":         "브라이턴",
  "Everton":                        "에버턴",
  "Fulham":                         "풀럼",
  "Crystal Palace":                 "크리스털 팰리스",
  "West Ham":                       "웨스트햄",
  "West Ham United":                "웨스트햄",
  "Wolverhampton":                  "울버햄튼",
  "Wolverhampton Wanderers":        "울버햄튼",
  "Wolves":                         "울버햄튼",
  "Burnley":                        "번리",
  "Nottingham Forest":              "노팅엄 포레스트",
  "Luton":                          "루턴 타운",
  "Luton Town":                     "루턴 타운",
  "Hull City":                      "헐 시티",
  "Coventry":                       "코번트리 시티",
  "Sunderland":                     "선덜랜드",
  "Sheffield":                      "셰필드 유나이티드",
  "Sheffield United":               "셰필드 유나이티드",
  "Sheffield Utd":                  "셰필드 유나이티드",
  "Leicester":                      "레스터 시티",
  "Leicester City":                 "레스터 시티",
  "Leeds":                          "리즈 유나이티드",
  "Leeds United":                   "리즈 유나이티드",
  "Southampton":                    "사우샘프턴",
  "Ipswich":                        "입스위치 타운",
  "Ipswich Town":                   "입스위치 타운",
  // La Liga
  "Real Madrid":                    "레알 마드리드",
  "Barcelona":                      "바르셀로나",
  "Atletico Madrid":                "아틀레티코 마드리드",
  "Atlético Madrid":                "아틀레티코 마드리드",
  "Sevilla":                        "세비야",
  "Valencia":                       "발렌시아",
  "Villarreal":                     "비야레알",
  "Real Sociedad":                  "레알 소시에다드",
  "Real Betis":                     "레알 베티스",
  "Betis":                          "레알 베티스",
  "Bilbao":                         "아틀레틱 빌바오",
  "Athletic Bilbao":                "아틀레틱 빌바오",
  "Athletic Club":                  "아틀레틱 빌바오",
  "Getafe":                         "헤타페",
  "Osasuna":                        "오사수나",
  "Mallorca":                       "마요르카",
  "Real Mallorca":                  "마요르카",
  "Girona":                         "지로나",
  "Rayo Vallecano":                 "라요 바예카노",
  "Alaves":                         "알라베스",
  "Deportivo Alaves":               "알라베스",
  "Celta Vigo":                     "셀타 비고",
  "Celta":                          "셀타 비고",
  "Las Palmas":                     "라스 팔마스",
  "Leganes":                        "레가네스",
  "Espanyol":                       "에스파뇰",
  "Valladolid":                     "바야돌리드",
  "Real Valladolid":                "바야돌리드",
  "Granada":                        "그라나다",
  "Cadiz":                          "카디스",
  "Malaga":                         "말라가",
  "Levante":                        "레반테",
  "Levante UD":                     "레반테",
  "Elche":                          "엘체",
  "Elche CF":                       "엘체",
  // Bundesliga
  "Bayern Munich":                  "바이에른 뮌헨",
  "Bayern":                         "바이에른 뮌헨",
  "Borussia Dortmund":              "보루시아 도르트문트",
  "Dortmund":                       "보루시아 도르트문트",
  "Leverkusen":                     "바이어 레버쿠젠",
  "Bayer Leverkusen":               "바이어 레버쿠젠",
  "Leipzig":                        "RB 라이프치히",
  "RB Leipzig":                     "RB 라이프치히",
  "Stuttgart":                      "슈투트가르트",
  "VfB Stuttgart":                  "슈투트가르트",
  "Frankfurt":                      "프랑크푸르트",
  "Eintracht Frankfurt":            "프랑크푸르트",
  "Wolfsburg":                      "볼프스부르크",
  "VfL Wolfsburg":                  "볼프스부르크",
  "Werder Bremen":                  "베르더 브레멘",
  "Bremen":                         "베르더 브레멘",
  "Hoffenheim":                     "호펜하임",
  "1899 Hoffenheim":                "호펜하임",
  "Freiburg":                       "프라이부르크",
  "SC Freiburg":                    "프라이부르크",
  "Mainz":                          "마인츠",
  "FSV Mainz 05":                   "마인츠",
  "Gladbach":                       "묀헨글라트바흐",
  "Borussia Monchengladbach":       "묀헨글라트바흐",
  "Borussia Mönchengladbach":       "묀헨글라트바흐",
  "Augsburg":                       "아우크스부르크",
  "FC Augsburg":                    "아우크스부르크",
  "Union Berlin":                   "우니온 베를린",
  "1. FC Union Berlin":             "우니온 베를린",
  "Heidenheim":                     "하이덴하임",
  "FC Heidenheim":                  "하이덴하임",
  "Bochum":                         "보훔",
  "VfL Bochum":                     "보훔",
  "St. Pauli":                      "장크트파울리",
  "FC St. Pauli":                   "장크트파울리",
  "Holstein Kiel":                  "홀슈타인 킬",
  "SV Elversberg":                  "엘버스베르크",
  "1. FC Köln":                     "쾰른",
  "Cologne":                        "쾰른",
  "SC Paderborn 07":                "파더보른",
  "Hamburger SV":                   "함부르크 SV",
  // Serie A
  "Juventus":                       "유벤투스",
  "Inter":                          "인터 밀란",
  "Inter Milan":                    "인터 밀란",
  "Milan":                          "AC 밀란",
  "AC Milan":                       "AC 밀란",
  "Napoli":                         "나폴리",
  "Roma":                           "AS 로마",
  "AS Roma":                        "AS 로마",
  "Lazio":                          "라치오",
  "Atalanta":                       "아탈란타",
  "Fiorentina":                     "피오렌티나",
  "Bologna":                        "볼로냐",
  "Torino":                         "토리노",
  "Udinese":                        "우디네세",
  "Genoa":                          "제노아",
  "Parma":                          "파르마",
  "Cagliari":                       "칼리아리",
  "Verona":                         "헬라스 베로나",
  "Hellas Verona":                  "헬라스 베로나",
  "Lecce":                          "레체",
  "Monza":                          "몬차",
  "Empoli":                         "엠폴리",
  "Venezia":                        "베네치아",
  "Como":                           "코모",
  // Serie B
  "Frosinone":                      "프로시노네",
  "Sassuolo":                       "사수올로",
  // UCL / Europe
  "PSG":                            "파리 생제르맹",
  "Paris Saint Germain":            "파리 생제르맹",
  "Paris Saint-Germain":            "파리 생제르맹",
  "Paris SG":                       "파리 생제르맹",
  "Benfica":                        "벤피카",
  "Porto":                          "포르투",
  "Sporting CP":                    "스포르팅",
  "PSV Eindhoven":                  "PSV 에인트호번",
  "Ajax":                           "아약스",
  "Feyenoord":                      "페예노르트",
  "Club Brugge":                    "클럽 브뤼헤",
  "Club Brugge KV":                 "클럽 브뤼헤",
  "Galatasaray":                    "갈라타사라이",
  "Shakhtar Donetsk":               "샤흐타르 도네츠크",
  "Red Bull Salzburg":              "잘츠부르크",
  "Monaco":                         "모나코",
  "Marseille":                      "마르세유",
  "Lyon":                           "리옹",
  "Lille":                          "릴",
  "Nice":                           "니스",
  // UCL / Europa / European competition (QA-confirmed API strings)
  "Slovan Bratislava":              "슬로반 브라티슬라바",
  "Dinamo Zagreb":                  "디나모 자그레브",
  "AEK Athens FC":                  "AEK 아테네",
  "Levski Sofia":                   "레프스키 소피아",
  "Viking":                         "바이킹",
  "Lask Linz":                      "LASK 린츠",
  "LASK Linz":                      "LASK 린츠",
  "LASK":                           "LASK 린츠",
  "Bodo/Glimt":                     "보되/글림트",
  "Slavia Praha":                   "슬라비아 프라하",
  "Hapoel Beer Sheva":              "하포엘 베에르셰바",
  "NEC Nijmegen":                   "NEC 나이메헌",
  "Celtic":                         "셀틱",
  "Celje":                          "첼레",
  "Sabah FA":                       "사바흐 FK",
  // Eredivisie / Laat: TEAM_REGISTRY에 있지만 TEAM_NAME_KO 폴백 보완
  "NAC Breda":                      "NAC 브레다",
  "PEC Zwolle":                     "PEC 즈볼러",
  "Go Ahead Eagles":                "고 어헤드 이글스",
  "Almere City":                    "알메러 시티",
  // Scottish Premiership (순위표 미등록 팀)
  "Kilmarnock":                     "킬마녹",
  "Ross County":                    "로스 카운티",
  "Livingston":                     "리빙스턴",
  "Dundee":                         "던디 FC",
  "St. Johnstone":                  "세인트 존스턴",
  // Dundee Utd: TEAM_REGISTRY에 있지만 TEAM_NAME_KO 폴백 보완
  "Dundee Utd":                     "던디 유나이티드",
  "Dundee United":                  "던디 유나이티드",
  // Ligue 1 / Ligue 2 (name-based fallback for ID mismatches and lower-division teams)
  "Angers":                         "앙제",
  "Le Havre":                       "르아브르",
  "Auxerre":                        "오세르",
  "Stade Brestois 29":              "브레스트",
  "Paris FC":                       "파리 FC",
  "Estac Troyes":                   "트루아",
  "Le Mans":                        "르망",
  // LaLiga 2
  "Deportivo La Coruna":            "데포르티보 라코루냐",
  "Racing Santander":               "라싱 산탄데르",
  // Eredivisie (API name variants & non-registry teams)
  "AZ Alkmaar":                     "AZ 알크마르",
  "Twente":                         "트벤터",
  "GO Ahead Eagles":                "고 어헤드 이글스",
  "Sparta Rotterdam":               "스파르타 로테르담",
  "Heerenveen":                     "헤이런베인",
  "Telstar":                        "텔스타르",
  "Utrecht":                        "위트레흐트",
  "Willem II":                      "빌럼 2세",
  "Cambuur":                        "캄뷔르",
  "Groningen":                      "흐로닝언",
  // Primeira Liga (API name variants & non-registry teams)
  "Arouca":                         "아루카",
  "Gil Vicente":                    "질 비센터",
  "GIL Vicente":                    "질 비센터",
  "Maritimo":                       "마리티무",
  "Estrela":                        "에스트렐라",
  "Academico Viseu":                "아카데미코 비세우",
  "Vitória SC":                     "비토리아 SC",
  "Vitoria SC":                     "비토리아 SC",
  "Famalicao":                      "파말리캉",
  "Rio Ave":                        "히우 아브",
  "Estoril":                        "에스토릴",
  "Alverca":                        "알베르카",
  "Casa Pia":                       "카사 피아",
  "Boavista":                       "보아비스타",
  "Moreirense":                     "모레이렌세",
  // Scottish Premiership (API name variants & non-registry teams)
  "Heart Of Midlothian":            "하츠",
  "Hearts":                         "하츠",
  "ST Mirren":                      "성 미렌",
  "St. Mirren":                     "성 미렌",
  "Motherwell":                     "머더웰",
  "Hibernian":                      "히베르니안",
  "Aberdeen":                       "애버딘",
  "Falkirk":                        "팔커크",
  "Rangers":                        "레인저스",
  // Süper Lig (API name variants & non-registry teams)
  "Beşiktaş":                       "베식타스",
  "Kocaelispor":                    "코자엘리스포르",
  "Trabzonspor":                    "트라브존스포르",
  "Gaziantep FK":                   "가지안테프 FK",
  "Alanyaspor":                     "알란야스포르",
  "Kasımpaşa":                      "카슴파샤",
  "Rizespor":                       "리제스포르",
  "Başakşehir":                     "이스탄불 바샥셰히르",
  "İstanbul Başakşehir":            "이스탄불 바샥셰히르",
  "Samsunspor":                     "삼순스포르",
  "Çorum FK":                       "초룸 FK",
  "Erzurumspor FK":                 "에르주룸스포르 FK",
  "Eyüpspor":                       "에윕스포르",
  "Göztepe":                        "괴즈테페",
  "Konyaspor":                      "코냐스포르",
  "Fenerbahçe":                     "페네르바체",
  "Sivasspor":                      "시바스스포르",
  "Amed":                           "아메드",
  "Gençlerbirliği S.K.":            "겐츨레르비를리이 SK",
  // MLS (API name variants & non-registry teams)
  "Vancouver Whitecaps":            "밴쿠버 화이트캡스",
  "Houston Dynamo":                 "휴스턴 다이나모",
  "Los Angeles FC":                 "LAFC",
  "FC Dallas":                      "FC 댈러스",
  "St. Louis City":                 "세인트루이스 시티",
  "San Jose Earthquakes":           "산호세 어스퀘이크스",
  "Colorado Rapids":                "콜로라도 래피즈",
  "Portland Timbers":               "포틀랜드 팀버스",
  "San Diego":                      "샌디에이고 FC",
  "Real Salt Lake":                 "레알 솔트레이크",
  "Seattle Sounders":               "시애틀 사운더스",
  "Austin":                         "오스틴 FC",
  "Inter Miami":                    "인터 마이애미",
  "LA Galaxy":                      "LA 갤럭시",
  "NYC FC":                         "뉴욕 시티 FC",
  "Atlanta United":                 "애틀랜타 유나이티드",
  "Chicago Fire":                   "시카고 파이어",
  "NY Red Bulls":                   "뉴욕 레드불스",
  "Columbus Crew":                  "콜럼버스 크루",
  "FC Cincinnati":                  "FC 신시내티",
  // Liga MX (API name variants & non-registry teams)
  "Club America":                   "클럽 아메리카",
  "Club América":                   "클럽 아메리카",
  "Guadalajara Chivas":             "치바스 과달라하라",
  "Chivas Guadalajara":             "치바스 과달라하라",
  "Toluca":                         "톨루카",
  "Club Tijuana":                   "클럽 티후아나",
  "Atlas":                          "아틀라스",
  "Cruz Azul":                      "크루스 아술",
  "Club Queretaro":                 "클럽 케레타로",
  "Leon":                           "레온",
  "Puebla":                         "푸에블라",
  "Monterrey":                      "CF 몬테레이",
  "CF Monterrey":                   "CF 몬테레이",
  "CF Pachuca":                     "파추카",
  "Pachuca":                        "파추카",
  "U.N.A.M. - Pumas":              "푸마스 UNAM",
  "Pumas UNAM":                     "푸마스 UNAM",
  "Necaxa":                         "네카사",
  "Atlante FC":                     "아틀란테 FC",
  "Tigres UANL":                    "티그레스 UANL",
  "Atletico San Luis":              "아틀레티코 산루이스",
  "Santos Laguna":                  "산토스 라구나",
  "FC Juarez":                      "FC 후아레스",
  // Brasileirão (API name variants & non-registry teams)
  "Atletico Paranaense":            "아틀레티코 파라나엔시",
  "Fluminense":                     "플루미넨시",
  "Cruzeiro":                       "크루제이루",
  "Coritiba":                       "코리티바",
  "RB Bragantino":                  "RB 브라간티누",
  "Vitoria":                        "비토리아",
  "Santos":                         "산투스",
  "Botafogo":                       "보타포구",
  "Gremio":                         "그레미우",
  "Mirassol":                       "미라솔",
  "Vasco DA Gama":                  "바스쿠 다 가마",
  "Chapecoense-sc":                 "샤페코엔시",
  "Flamengo":                       "플라멩고",
  "Palmeiras":                      "팔메이라스",
  "Corinthians":                    "코린치안스",
  "São Paulo":                      "상파울루",
  "Atlético-MG":                    "아틀레티코 미네이루",
  "Internacional":                  "인테르나시오날",
  "Remo":                           "헤무",
  // Saudi Pro League (API name variants & non-registry teams)
  "Al-Hilal Saudi FC":              "알 힐랄",
  "Al-Hilal":                       "알 힐랄",
  "Al-Nassr":                       "알 나스르",
  "Al-Qadisiyah FC":                "알 카디시아",
  "Al-Ittihad FC":                  "알 이티하드",
  "Al-Ittihad":                     "알 이티하드",
  "Al-Ahli Jeddah":                 "알 아흘리",
  "Al-Ahli":                        "알 아흘리",
  "Al-Ettifaq":                     "알 에티파크",
  "Al Diriyah":                     "알 디리야흐",
  "Al-Hazm":                        "알 하즘",
  "Al-Fayha":                       "알 파이하",
  "Al Riyadh":                      "알 리야드",
  "Al-Riyadh":                      "알 리야드",
  "Al Taawon":                      "알 타아원",
  "Al-Taawoun":                     "알 타아원",
  "Al Shabab":                      "알 샤밥",
  "Al-Shabbab":                     "알 샤밥",
  "Al-Fateh":                       "알 파테흐",
  "Al-Faisaly FC":                  "알 파이살리",
  "Al-Faisaly":                     "알 파이살리",
  "Abha":                           "아브하",
  "Al Khaleej Saihat":              "알 칼리즈",
  // K League 1 (API name variants)
  "FC Seoul":                       "서울 FC",
  "Jeonbuk Motors":                 "전북 현대",
  "Jeonbuk Hyundai":                "전북 현대",
  "Ulsan Hyundai FC":               "울산 HD",
  "Ulsan HD":                       "울산 HD",
  "Daejeon Citizen":                "대전 시티즌",
  "Pohang Steelers":                "포항 스틸러스",
  "FC Anyang":                      "FC 안양",
  "Incheon United":                 "인천 유나이티드",
  "Gimcheon Sangmu FC":             "김천 상무",
  "Gimcheon Sangmu":                "김천 상무",
  "Gwangju FC":                     "광주 FC",
  // J1 League (API name variants & non-registry teams)
  "Kashima":                        "가시마 앤틀러스",
  "Kashima Antlers":                "가시마 앤틀러스",
  "FC Tokyo":                       "FC 도쿄",
  "Machida Zelvia":                 "마치다 젤비아",
  "Kawasaki Frontale":              "가와사키 프론탈레",
  "Tokyo Verdy":                    "도쿄 베르디",
  "Urawa":                          "우라와 레즈",
  "Urawa Reds":                     "우라와 레즈",
  "Yokohama F. Marinos":            "요코하마 F. 마리노스",
  "Kashiwa Reysol":                 "가시와 레이솔",
  "Mito Hollyhock":                 "미토 홀리혹",
  "JEF United Chiba":               "JEF 유나이티드 지바",
  // Europa League extras
  "Anderlecht":                     "안더레흐트",
  "Ararat-Armenia":                 "아라라트-아르메니아",
  "Jagiellonia":                    "야기엘로니아",
  "Lech Poznan":                    "레흐 포즈난",
  "Olympiakos Piraeus":             "올림피아코스",
  "Omonia Nicosia":                 "오모니아 니코시아",
  "Sparta Praha":                   "스파르타 프라하",
  "Sturm Graz":                     "슈투름 그라츠",
  "Union St. Gilloise":             "위니옹 생질루아즈",
  "Plzen":                          "빅토리아 플젠",
  "Lillestrom":                     "릴레스트룀",
  "OFI":                            "OFI 크레타",
  "Torreense":                      "토렌세",
};

/** Look up a team's Korean name by its English API name. */
export function getTeamNameKo(rawName: string): string | undefined {
  return TEAM_NAME_KO[rawName];
}

/**
 * Resolve display name — Korean-first, English fallback.
 * Priority: nameKo param → TEAM_NAME_KO lookup → raw name
 */
export function getDisplayTeamName(name: string, nameKo?: string): string {
  return nameKo ?? getTeamNameKo(name) ?? name;
}
